const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const data=JSON.parse(fs.readFileSync('learning/content.json','utf8'));
const scope={};vm.createContext(scope);vm.runInContext(fs.readFileSync('learning/generator.js','utf8'),scope);const generator=scope.LearningGenerator;
// A separate normalized content oracle excludes template identity and presentation positions.
function semantic(q){if(q.stages)return q.stages.map(semantic);if(q.nodes)return q.nodes;return {mode:q.mode,prompt:q.prompt||'',narration:q.narration||'',scene:q.scene||[],items:q.items||[],constraints:q.constraints||[],accepted:q.accepted||[],options:(q.options||[]).map((o,i)=>[o,(q.answers||[]).includes(i)]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),observation:q.observation||''};}
let families=0,min=Infinity,records=0;
for(const [sub,cfg] of Object.entries(data))for(const lev of cfg.levels)for(const fam of lev.families){families++;const set=new Set(fam.tasks.map(q=>JSON.stringify(semantic(q))));assert(set.size>=12,sub+' '+fam.name+' needs twelve substantive samples');min=Math.min(min,set.size);for(const q of fam.tasks){const copy=JSON.parse(JSON.stringify(q));copy.id='other-id';assert.equal(generator.signature(q),generator.signature(copy),'Changing only ID is not new content');if(q.options){let reversed=JSON.parse(JSON.stringify(q));reversed.options.reverse();reversed.answers=q.answers.map(i=>q.options.length-1-i);assert.equal(generator.signature(q),generator.signature(reversed),'Choice positions do not make new content');}
if(q.generator)for(let n=0;n<61;n++){const r=generator.materialize(q,n),g=q.generator;if(g.type==='change-record'){const m=r.prompt.match(/A first (\d+), later (\d+)\. B first (\d+), later (\d+)/);assert(m);const [a,b,c,d]=m.slice(1).map(Number);assert.equal(b-a,g.delta);assert.equal(c,d);assert(a>=0&&b>=0);if(fam.name==='Compare records')assert(r.options[0].label.includes(b>a?'increased':'decreased'));}else{const m=r.prompt.match(/A (\d+), (\d+), (\d+); B (\d+), (\d+), (\d+)/);assert(m);let v=m.slice(1).map(Number);assert(Math.max(...v.slice(0,3))<Math.min(...v.slice(3)));assert(r.options[0].label.includes('smaller'));}records++;}
}}
function solve(doc,q){function click(prefix){const b=[...doc.querySelectorAll('button')].find(x=>(x.getAttribute('aria-label')||x.textContent).startsWith(prefix));assert(b,prefix);b.click();}for(const s of q.stages||[q]){if(s.mode==='branch'){let k='start';while(!q.nodes[k].end){const o=q.nodes[k].options[0];click('Story choice 1:');k=o.to;}}else if(s.mode==='predict'){click('Predict option 1:');click('Observe →');}else if(s.mode==='order'){let ids=s.items.map((_,i)=>i);if(s.constraints){function perm(a){return a.length?a.flatMap((x,i)=>perm(a.filter((_,j)=>j!==i)).map(v=>[x,...v])):[[]];}ids=perm(ids).find(v=>s.constraints.every(([a,b])=>v.indexOf(a)<v.indexOf(b)));}for(const i of ids)click('Add card '+(i+1)+':');}else for(const i of s.answers)click('Choose option '+(i+1)+':');}}
let rounds=0;
for(const [sub,cfg] of Object.entries(data)){
 const html=fs.readFileSync(sub+'.html','utf8'),dom=new JSDOM(html,{url:'https://example.test',runScripts:'dangerously',beforeParse(w){w.Math.random=()=>0;}}),d=dom.window.document;
 function click(prefix){const b=[...d.querySelectorAll('button')].find(x=>(x.getAttribute('aria-label')||x.textContent).startsWith(prefix));assert(b,prefix);b.click();}
 for(let l=1;l<=6;l++){click('Level '+l+':');for(let f=0;f<3;f++){click('Activity '+(f+1)+':');const recent=[];for(let n=0;n<25;n++){const play=d.getElementById('play'),source=cfg.levels[l-1].families[f].tasks.find(q=>q.id===play.getAttribute('data-task-id'));const q=generator.materialize(source,Number(play.getAttribute('data-variant'))),sig=JSON.stringify(semantic(q));assert(!recent.slice(-10).includes(sig),sub+' '+l+' '+f+' repeat within ten');recent.push(sig);solve(d,q);assert(!d.getElementById('next').hidden);click('→ Another question');rounds++;}click('Back');}click('Back');}
 const stored=dom.window.localStorage.getItem('kll-'+sub+'-recent-v1');assert(stored);const history=JSON.parse(stored);
 dom.window.close();
 const reload=new JSDOM(html,{url:'https://example.test',runScripts:'dangerously',beforeParse(w){w.Math.random=()=>0;w.localStorage.setItem('kll-'+sub+'-recent-v1',stored);}}),rd=reload.window.document;
 [...rd.querySelectorAll('.level')][0].click();[...rd.querySelectorAll('.family')][0].click();const play=rd.getElementById('play'),q=cfg.levels[0].families[0].tasks.find(q=>q.id===play.getAttribute('data-task-id'));assert(!history['1-0'].includes(generator.signature(generator.materialize(q,Number(play.getAttribute('data-variant'))))),'Reload preserves recent exclusions');reload.window.close();
}
console.log('PASS:',families,'families with at least',min,'distinct samples;',rounds,'constant-RNG rounds without repeats in previous ten;',records,'independently checked runtime records; reload and option-order-independent history.');
