const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom'),acorn=require('acorn');
const html=fs.readFileSync('math.html','utf8'),art=JSON.parse(html.match(/var art=(\{.*?\});/)[1]);acorn.parse(html.match(/<script>([\s\S]*?)<\/script>/)[1],{ecmaVersion:5});assert(!/setInterval|setTimeout|id="check"|Suggested age/.test(html));
function launch(blocked=false,seed=1){return new JSDOM(html,{url:'https://example.test/math.html',runScripts:'dangerously',beforeParse(w){w.Math.random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};if(blocked)Object.defineProperty(w,'localStorage',{get(){throw Error('blocked')}})}});}
const bs=(d,id)=>[...d.getElementById(id).querySelectorAll('button')],click=(d,id)=>d.getElementById(id).click(),nums=d=>(d.getElementById('prompt').textContent.match(/\d+/g)||[]).map(Number),nextHidden=d=>assert.equal(d.getElementById('next').style.display,'none');
function open(d,k,l){bs(d,'activities')[k].click();assert.equal(bs(d,'levels').length,6);bs(d,'levels')[l-1].click();assert.equal(d.getElementById('stage').getAttribute('aria-label'),'Level '+l);}
function answer(d,n){const prev=d.getElementById('scene').innerHTML;bs(d,'choices').find(x=>x.textContent!==String(n)).click();assert.equal(d.getElementById('scene').innerHTML,prev);nextHidden(d);const correct=bs(d,'choices').find(x=>x.textContent===String(n));assert(correct,'Missing answer '+n);correct.click();}
function solve(d,k,l,r){
 if(k===0){if(l===3){let [whole,part]=nums(d);assert(whole>=8&&whole<=12);answer(d,whole-part);}else{const ids=[...d.querySelectorAll('.rabbit-card')].map(x=>x.id);let taps=0;while(bs(d,'scene').length){bs(d,'scene')[0].click();taps++;assert.deepEqual([...d.querySelectorAll('.rabbit-card')].map(x=>x.id),ids);}assert.equal(taps,ids.length*(l===2?2:1));}}
 if(k===1){if(l===3){const [a,b]=nums(d);if(r===1){assert.equal(bs(d,'choices').length,3);nextHidden(d);click(d,'depart-group');assert.equal(d.querySelectorAll('.departed-person').length,b);nextHidden(d);}answer(d,r===0?a+b:a-b);if(r===0)assert.equal(d.getElementById('whole-value').parentNode.getAttribute('aria-label'),'Whole group: '+(a+b));}else if(r===0){while(bs(d,'waiting').length)bs(d,'waiting')[0].click();}else if(r===1){bs(d,'scene')[0].click();assert.equal(d.getElementById('next').style.display,'block');let before=d.getElementById('whole').textContent;bs(d,'scene')[0].click();assert.notEqual(d.getElementById('whole').textContent,before);let p=d.getElementById('whole').textContent.match(/\d+/g).map(Number);assert.equal(p[0],p[1]+p[2]);}else if(l===2){const [a,b]=nums(d);answer(d,a-b);}else{while(bs(d,'wagon1').length)bs(d,'wagon1')[0].click();}}
 if(k===2){if(l===1){const choices=bs(d,'scene'),n=choices.map(x=>x.querySelectorAll('.rail').length),correct=n[0]>n[1]?0:1;choices[1-correct].click();nextHidden(d);choices[correct].click();}else if(l===2){while(bs(d,'measure').length)bs(d,'measure')[0].click();nextHidden(d);answer(d,d.querySelectorAll('#measure .rail').length);}else{let [a,b]=nums(d);answer(d,a-b);assert.equal(d.querySelectorAll('#short-track .rail').length,a);}}
 if(k===3){if(l===1){let dots=[...d.querySelectorAll('.dot')],n=dots.length;assert(n>=2&&n<=4);const xy=dots.map(x=>[parseInt(x.style.left),parseInt(x.style.top)]);for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)assert(Math.hypot(xy[i][0]-xy[j][0],xy[i][1]-xy[j][1])>=24);answer(d,n);}else if(l===2){let [a,b]=nums(d);answer(d,a+b);}else if(r===2){let [a,b]=nums(d);answer(d,b-a);}else answer(d,d.querySelectorAll('.counter:not(.removed)').length);}
 if(k===4){for(let step=0;step<(l===3?2:1);step++){let imgsOrder=bs(d,'choices').map(x=>x.querySelector('img').src),imgs=[...d.querySelectorAll('#sequence img')],expected=imgs[imgs.length%Number(d.getElementById('sequence').getAttribute('data-unit-length'))].src;bs(d,'choices').find(x=>x.querySelector('img').src!==expected).click();nextHidden(d);bs(d,'choices').find(x=>x.querySelector('img').src===expected).click();if(l===3&&step===0){nextHidden(d);assert.deepEqual(bs(d,'choices').map(x=>x.querySelector('img').src),imgsOrder,'Multi-step answer positions stay stable');}}}
 if(k===5){assert.equal(bs(d,'sort-bins').length,0);assert.equal(d.querySelectorAll('.basket').length,l===3?4:2);while(bs(d,'sort-source').length){let item=bs(d,'sort-source')[0],img=item.querySelector('img'),small=l===3?img.className==='sort-small':img.src===art.circlelittle||img.src===art.squarelittle,square=img.src===art.square||img.src===art.squarelittle,bin=l===3?Number(square)*2+Number(small):l===2&&r===1?Number(small):Number(square);item.click();let count=bs(d,'sort-source').length,slots=d.getElementById('sort-source').children.length;click(d,'sort-bin-'+((bin+1)%(l===3?4:2)));assert.equal(bs(d,'sort-source').length,count);click(d,'sort-bin-'+bin);assert.equal(d.getElementById('sort-source').children.length,slots,'Source slots stay stable');}assert.equal(bs(d,'sort-bins').length,0);}
 if(k===6){let goal=['circle','square','triangle'][r],parent=l===3?'scene':'choices',label='Choose '+goal;bs(d,parent).find(x=>x.getAttribute('aria-label')!==label).click();nextHidden(d);let found=0;while(bs(d,parent).some(x=>x.getAttribute('aria-label')===label)){bs(d,parent).find(x=>x.getAttribute('aria-label')===label).click();found++;if(l===3&&found<3)nextHidden(d);}assert.equal(found,l===3?3:1);}
 if(k===7){let counts=[d.querySelectorAll('#group0 img').length,d.querySelectorAll('#group1 img').length];if(l===1){let label=counts[0]===counts[1]?'Equal groups':r===2?(counts[0]<counts[1]?'Choose first group':'Choose second group'):(counts[0]>counts[1]?'Choose first group':'Choose second group');bs(d,'choices').find(x=>x.getAttribute('aria-label')!==label).click();nextHidden(d);bs(d,'choices').find(x=>x.getAttribute('aria-label')===label).click();}else{if(l===3){let larger=counts[0]>counts[1]?0:1;bs(d,'choices')[1-larger].click();nextHidden(d);bs(d,'choices')[larger].click();nextHidden(d);assert.equal(d.querySelectorAll('.extra-object').length,Math.abs(counts[0]-counts[1]));for(let row=0;row<2;row++)assert.equal(d.querySelectorAll('#group'+row+' .paired-object, #group'+row+' .extra-object').length,counts[row]);}answer(d,Math.abs(counts[0]-counts[1]));}}
 if(k===8){if(l===1){let ids=['space-above','space-below','space-inside'];bs(d,ids[(r+1)%3])[0].click();nextHidden(d);bs(d,ids[r])[0].click();}else{for(let step=0;step<(l===2?2:3);step++){let src=d.querySelector('#prompt img').src,cells=[...d.querySelectorAll('.model-cell')],cell=cells.findIndex(x=>x.querySelector('img')?.src===src),label=`Place in row ${Math.floor(cell/3)+1} column ${cell%3+1}`;bs(d,'copy-grid').find(x=>x.getAttribute('aria-label')!==label).click();nextHidden(d);bs(d,'copy-grid').find(x=>x.getAttribute('aria-label')===label).click();if(step<(l===2?1:2))nextHidden(d);}assert.equal(d.querySelectorAll('.placed-object').length,l===2?2:3);}}
}
const firstVariants=new Set();
for(const seed of [12345,42017,99001,20261009])for(let l=1;l<=3;l++)for(let k=0;k<9;k++){
 let dom=launch(false,seed),d=dom.window.document;open(d,k,l);let variants=[],scenes=new Set();
 for(let q=0;q<12;q++){
  nextHidden(d);const before=d.getElementById('scene').innerHTML;click(d,'next');assert.equal(d.getElementById('scene').innerHTML,before,'Cannot skip an unanswered question');
  assert.equal(d.getElementById('progress').getAttribute('aria-label'),`Question ${q+1}; continue at your own pace`);
  const r=Number(d.getElementById('play').getAttribute('data-variant'));variants.push(r);if(q===0)firstVariants.add(r);scenes.add(d.getElementById('prompt').innerHTML+before+d.getElementById('choices').innerHTML);
  solve(d,k,l,r);assert.equal(d.getElementById('next').style.display,'block',`${l}/${k}/${q}`);
  if(!(k===1&&l<3&&r===1))assert.equal(bs(d,'scene').length+bs(d,'choices').length,0,'Completed references are passive');
  click(d,'next');assert.equal(d.getElementById('play').style.display,'block');assert.equal(d.getElementById('stage').getAttribute('aria-label'),'Level '+l);
 }
 for(let q=0;q<12;q+=3)assert.equal(new Set(variants.slice(q,q+3)).size,3,'Shuffled bag balances task variants');
 for(let q=1;q<12;q++)assert.notEqual(variants[q],variants[q-1],'No immediately repeated task variant');
 assert(scenes.size>1,'Repeated practice must vary the scene');assert.equal(JSON.parse(dom.window.localStorage.getItem('kindle-math-levels-v3'))[(l+2)+'-'+k],true);
 click(d,'back');assert.equal(d.getElementById('menu').style.display,'block');bs(d,'levels')[l-1].click();assert.match(d.getElementById('progress').getAttribute('aria-label'),/^Question 1;/);
 if(l<3){solve(d,k,l,Number(d.getElementById('play').getAttribute('data-variant')));assert.equal(d.getElementById('advance').getAttribute('aria-label'),'Try level '+(l+1));click(d,'advance');assert.equal(d.getElementById('stage').getAttribute('aria-label'),'Level '+(l+1));assert.match(d.getElementById('progress').getAttribute('aria-label'),/^Question 1;/);}
 dom.window.close();
}
assert.equal(firstVariants.size,3,'First question is not fixed');
let dom=launch(true),d=dom.window.document;open(d,0,1);assert.match(d.getElementById('save-note').textContent,/unavailable/);while(bs(d,'scene').length)bs(d,'scene')[0].click();assert.equal(d.getElementById('next').style.display,'block');dom.window.close();
dom=launch();dom.window.localStorage.setItem('kindle-math-stories-v2','{"3-0":true}');click(dom.window.document,'clear');assert.equal(dom.window.localStorage.getItem('kindle-math-stories-v2'),'{"3-0":true}');dom.window.close();
console.log('PASS: ES5; 9 topics × 3 levels × 12 questions × 4 seeds, uncapped same-level continuation, shuffled variants, varied first questions, visible and hidden parts, multi-step decisions, four-way sorting, patterns, spatial models, retries, passive references, progression and storage fallback.');
