"""Original reviewed examples. Frameworks guide objectives, not copied course material."""
import json
from pathlib import Path
R=Path(__file__).resolve().parent.parent
D={};serial=0

def C(label,art=None,text=None):
 x={'label':label}
 if art:x['art']=art
 if text is not None:x['text']=text
 return x

def T(s):return C(s,text=s)
def A(name):return C(name,name)
def Q(prompt,options,answer=0,explain='',scene=None,cue='Choose the answer.',hint=None,narration=None):
 global serial;serial+=1
 x={'id':'task-'+str(serial),'mode':'choice','prompt':prompt,'cue':cue,'options':[T(o) if isinstance(o,str) else o for o in options],'answers':answer if isinstance(answer,list) else [answer],'explain':explain,'scene':scene or []}
 if hint:x['hint']=hint
 if narration:x['narration']=narration
 return x

def O(prompt,items,explain='',constraints=None,accepted=None):
 q=Q(prompt,[],explain=explain,cue='Tap cards in order. Undo to change your plan.');q.update(mode='order',items=[T(x) if isinstance(x,str) else x for x in items])
 if constraints:q['constraints']=constraints
 if accepted:q['accepted']=accepted
 return q

def M(prompt,opts,answers,explain,scene=None):
 q=Q(prompt,opts,answers,explain,scene,'Find every picture that follows the rule.');q['mode']='multi';return q

def S(a,b):
 return {'id':a['id']+'-steps','stages':[a,b],'guide':'Solve each step in order. The next cue follows your answer; pictures and text remain reference material.'}

def F(name,description,tasks):return {'name':name,'description':description,'tasks':tasks}
def subject(id,title,intro,guide,goals,previews):
 D[id]={'id':id,'title':title,'intro':intro,'guide':guide,'levels':[{'name':n,'goal':g,'preview':p,'families':[]} for (n,g),p in zip(goals,previews)]}
def put(id,l,*families):D[id]['levels'][l-1]['families']=list(families)
def feat(s='circle',f='plain',z='large'):return C(z+' '+f+' '+s,s+'-'+f+'-'+z)

subject('logic','Logic Detective','Pictures first. Levels describe reasoning, not age. A grown-up may explain a new rule once.','Read clues aloud when needed. Keep the clue visible. Ask what changed or which rule helped. Different valid plans are accepted.',[
 ('Notice','Compare one visible feature'),('Connect','Use a relationship or one rule'),('Combine','Combine two features or apply a transformation'),('Use clues','Use two clues together'),('Plan','Arrange several things under constraints'),('Explain','Test a rule or choose useful evidence')],['＝ picture','key → door','shape + pattern','clue A + clue B','A → B; A → C','rule → exception'])
# Level 1: quantity of cards is fixed, visual target changes semantically.
match=[];changed=[];parts=[]
for shape in ['circle','square','triangle']:
 for fill in ['plain','striped','filled']:
  other=[s for s in ['circle','square','triangle'] if s!=shape]
  match.append(Q('＝ → ?', [feat(shape,fill),feat(other[0],fill),feat(other[1],fill)],explain='The outline and pattern match.',scene=[feat(shape,fill)],cue='Find the same picture.'))
for shape in ['circle','square','triangle']:
 changed.append(Q('Pattern changed → ?', [feat(shape,'striped'),feat(shape),feat(shape)],explain='This picture has stripes; the target is plain.',scene=[feat(shape)],cue='Find the picture with a changed pattern.'))
 parts.append(Q('Part → whole', [feat(shape),feat('square' if shape!='square' else 'circle'),feat('triangle' if shape!='triangle' else 'circle')],explain='The visible outline belongs to this whole picture.',scene=[dict(feat(shape),crop=True)],cue='Find the whole picture.'))
put('logic',1,F('Same picture','＝ Compare outline and pattern.',match),F('What changed?','One feature changes; find it.',changed),F('Part and whole','A partial picture points to its whole.',parts))
put('logic',2,
 F('Useful pairs','Match things used together.',[Q('→ ?', [A('door'),A('book'),A('cup')],scene=[A('key')],explain='A key can open a matching lock on a door.'),Q('→ ?', [A('shoe'),A('umbrella'),A('book')],scene=[A('sock')],explain='Socks and shoes are worn on feet.')]),
 F('One pictured rule','Find all pictures with the shown pattern.',[M('Stripes only',[feat('circle','striped'),feat('square'),feat('triangle','striped')],[0,2],'Both selected pictures have stripes.',[feat('square','striped')]),M('Filled only',[feat('square','filled'),feat('circle','plain'),feat('triangle','filled')],[0,2],'Both selected pictures are filled.',[feat('circle','filled')])]),
 F('First, then','Arrange familiar steps.',[O('Feet: first → last',[A('sock'),A('shoe')],'Socks go on before shoes.'),O('Hands: first → last',[A('wash'),A('dry')],'Wash wet hands before drying them.')]))
put('logic',3,
 F('Two features','Find the pictured shape AND pattern.',[Q('Circle + stripes',[feat('circle','striped'),feat('circle'),feat('square','striped')],scene=[feat('circle'),feat('square','striped')],explain='The answer has both the round outline and stripes.'),Q('Square + filled',[feat('square','filled'),feat('circle','filled'),feat('square')],scene=[feat('square'),feat('circle','filled')],explain='The answer has both the square outline and filled pattern.')]),
 F('Apply a change','Use the demonstrated transformation.',[Q('Same change → ?', [feat('square','filled'),feat('square'),feat('circle','filled')],scene=[feat('circle'),feat('circle','filled'),feat('square')],explain='Keep the outline; change plain to filled.'),Q('Same change → ?', [feat('triangle','striped'),feat('triangle','filled'),feat('square','striped')],scene=[feat('square'),feat('square','striped'),feat('triangle')],explain='Keep the outline; add stripes.')]),
 F('Picture patterns','Follow the shown repeating rule.',[Q('○ □ ○ □ ○ ?', [feat('square'),feat('triangle'),feat('circle')],explain='Circle and square alternate.'),Q('▲ ▲ ○ ▲ ▲ ○ ▲ ▲ ?', [feat('circle'),feat('triangle'),feat('square')],explain='Two triangles are followed by one circle.')]))
put('logic',4,
 F('Use both clues','One clue alone is not enough.',[Q('Round outline AND not filled',[feat('circle'),feat('circle','filled'),feat('square')],explain='Only the plain circle meets both clues.',hint='Check each clue against every picture.'),Q('Stripes AND not round',[feat('square','striped'),feat('circle','striped'),feat('square')],explain='Only the striped square meets both clues.')]),
 F('Before and after','Meet both order constraints.',[O('Rabbit before bear. Bear before train.',[A('rabbit0'),A('bear0'),A('engine')],'Both order clues are satisfied.',[[0,1],[1,2]]),O('Key before door. Door before cup.',[A('key'),A('door'),A('cup')],'The order follows both clues.',[[0,1],[1,2]])]),
 F('Two clues, one object','Combine functions and features.',[Q('Has wheels. Travels on rails.',[A('engine'),A('bus'),A('boat')],explain='A train has wheels and travels on rails.'),Q('Has pages. You can read its story.',[A('book'),A('door'),A('cup')],explain='The book has pages that carry a story.')]))
put('logic',5,
 F('Assign the places','Left-to-right positions satisfy every clue.',[O('Three places, left → right. Rabbit is not in the middle. Bear is left of rabbit. Train is right of rabbit.',[A('bear0'),A('rabbit0'),A('engine')],'Bear, rabbit, train fits all three clues.',[[0,1],[1,2]]),O('Three places, left → right. Book is left of cup. Key is not at an end.',[A('book'),A('key'),A('cup')],'Book, key, cup fits the position clues.',[[0,1],[1,2]])]),
 F('Make a workable plan','Several orders can be valid.',[O('Wash must happen before eating. Dry must happen after washing. Eating and drying may occur in either order in this toy plan.',[A('wash'),A('eat'),A('dry')],'Both dependencies are met.',[[0,1],[0,2]]),O('Open the door before bringing in either the book or the cup. Those two deliveries may happen in either order.',[A('door'),A('book'),A('cup')],'Either delivery order is valid after opening.',[[0,1],[0,2]])]),
 F('Repair a plan','Choose a change that fixes all shown rules.',[Q('Plan: shoes → socks → outside. Rule: socks before shoes, and both before outside.', ['Swap shoes and socks','Move outside first','Remove socks'],explain='Swapping the first two steps satisfies both rules.'),Q('Plan: eat → wash → dry. Rule: wash before eating and wash before drying.', ['Move wash to the start','Move dry to the start','Move wash to the end'],explain='Both eating and drying now follow washing.')]))
put('logic',6,
 F('Find a counterexample','One example can disprove an all-rule.',[Q('Rule: every picture is striped. Which picture disproves it?',[feat('triangle'),feat('circle','striped'),feat('square','striped')],explain='The plain triangle is not striped.'),Q('Rule: every picture is round. Which picture disproves it?',[feat('square'),feat('circle'),feat('circle','filled')],explain='The square is not round.')]),
 F('Which clue helps?','Choose evidence that separates two possibilities.',[Q('Both candidates have wheels: train or bus. Which question distinguishes them?',['Does it travel on rails?','Does it have wheels?','Can it carry people?'],explain='The rails clue separates these two pictured candidates.'),Q('The object is either a cup or a book. We know it is on a table. Can we identify it?',['Not enough information','It must be a cup','It must be a book'],explain='Both objects can be on a table. A new clue is needed.')]),
 F('Plan, then explain','Use a valid arrangement and its reason.',[S(O('Rabbit must come before both bear and train. Bear and train can be in either order.',[A('rabbit0'),A('bear0'),A('engine')],'',[[0,1],[0,2]]),Q('Why does your plan work?',['Rabbit comes before both others','Bear always comes first','Train is always last'],explain='Both possible orders keep rabbit before the others.')),S(O('Key must come before both book and cup. Book and cup can be in either order.',[A('key'),A('book'),A('cup')],'',[[0,1],[0,2]]),Q('What rule matters?',['Key comes before both others','Cup always comes first','Book must come last'],explain='The relative order of book and cup is unrestricted.'))]))
# Two language packs share meaning inventories, not assumed proficiency or a phonics claim.
for lang in ['chinese','english']:
 zh=lang=='chinese'
 def L(c,e):return c if zh else e
 subject(lang,L('中文故事屋','English Explorer'),L('看图、说话、读故事。低级词义题需要大人读提示；不要求三岁孩子独立认字。','Picture vocabulary and print practice. A grown-up narrates early word tasks. Silent spelling is not a phonics lesson.'),L('大人可以读题、追问，再让孩子用自己的话说一说。认识图画不等于读懂文字。','Read the prompt aloud when needed; invite the child to tell the story. Word-picture matching is not a full reading assessment.'),[
 (L('观察与听说','Notice and listen'),L('熟悉物品和动作','Recognize familiar objects and actions')),
 (L('认识文字','Connect print'),L('常见字、标签和生活顺序','Recognize letter forms, labels and simple order')),
 (L('组合词语','Build meaning'),L('组合熟悉词语，理解关系','Construct familiar words and phrases')),
 (L('读懂短句','Read sentences'),L('理解动作、位置和句子顺序','Understand actions, positions and sentence order')),
 (L('理解故事','Connect a story'),L('联系几句话中的信息','Connect information across short sentences')),
 (L('推断与解释','Infer and explain'),L('用故事中的证据支持答案','Use passage evidence to support an answer'))],['picture → word','print → picture','parts → word','sentence → scene','story → who / why','clue → explanation'])
 nouns=[('杯子','cup','cup'),('书','book','book'),('钥匙','key','key'),('小猫','cat','cat'),('小狗','dog','dog'),('火车','train','engine')]
 vocab=[]
 for i,(ch,en,art) in enumerate(nouns):
  others=[nouns[(i+j)%len(nouns)] for j in [1,2]]
  vocab.append(Q('',[A(art)]+[A(o[2]) for o in others],explain=L('这幅图表示'+ch+'。','This picture represents '+en+'.'),cue=L('听大人读词，再选图片。','Listen to the grown-up, then choose a picture.'),narration=L('大人读：'+ch,'Grown-up says: '+en)))
 actions=[]
 for ch,en,art in [('睡觉','sleep','sleep'),('洗手','wash hands','wash'),('跑步','run','run')]:
  wrong=[a for a in ['sleep','wash','run'] if a!=art]
  actions.append(Q('',[A(art)]+[A(x) for x in wrong],explain=L('这是'+ch+'。','The picture shows '+en+'.'),cue=L('听一听，选动作。','Listen, then choose the action.'),narration=L('大人读：'+ch,'Grown-up says: '+en)))
 assoc=[Q('',[A('cup'),A('shoe'),A('book')],explain=L('杯子可以用来喝水。','A cup can hold drinking water.'),cue=L('听故事，选物品。','Listen to the scene and choose an object.'),narration=L('小兔口渴了，想喝水。选一个喝水用的东西。','Rabbit is thirsty. Choose something used for drinking.')),Q('',[A('bed'),A('key'),A('umbrella')],explain=L('床是睡觉的地方。','A bed is a place to sleep.'),cue=L('听故事，选物品。','Listen to the scene and choose an object.'),narration=L('小熊困了，想睡觉。选一个可以睡觉的地方。','Bear is tired and wants to sleep. Choose a place for sleeping.'))]
 put(lang,1,F(L('看图认词','Picture words'),L('大人读词，孩子选图。','Adult narration; choose a picture.'),vocab),F(L('动作词','Action words'),L('用动作图理解词义。','Meaning through pictured actions.'),actions),F(L('听小故事','A tiny story'),L('从生活情境理解词语。','Use a familiar scene to understand words.'),assoc))
 chars=[Q('山',[A('house'),A('plant'),A('ramp')],answer=2,explain='这张图中的斜坡形状像一座小山。',cue='找对应的图。'),Q('水',[A('water'),A('shoe'),A('book')],explain='水字对应水滴图。',cue='找对应的图。')] if zh else [Q('A',['a','b','d'],explain='A and a are the same letter in two cases.'),Q('B',['b','p','d'],explain='B and b are the same letter in two cases.'),Q('D',['d','b','p'],explain='D and d are the same letter in two cases.')]
 # Avoid teaching a ramp as the conventional 山 referent: use an authored mountain PNG.
 if zh:chars[0]['options']=[A('mountain'),A('house'),A('plant')];chars[0]['answers']=[0];chars[0]['explain']='山字对应山的图画。'
 labels=[Q(L('门','door'),[A('door'),A('cup'),A('sock')],explain=L('这是门。','This is a door.')),Q(L('书','book'),[A('book'),A('ball'),A('umbrella')],explain=L('这是书。','This is a book.'))]
 if not zh:labels += [Q('cat',[A('cat'),A('dog'),A('fish')],explain='This is a cat.')]
 seq=[O(L('洗手：先 → 后','Hands: first → last'),[A('wash'),A('dry')],L('先洗手，再擦干。','Wash before drying.')),O(L('穿鞋：先 → 后','Getting ready: first → last'),[A('sock'),A('shoe')],L('先穿袜子，再穿鞋。','Socks before shoes.'))]
 put(lang,2,F(L('字和图','Letter pairs'),L('从熟悉符号开始。','Match introduced letter forms.'),chars),F(L('生活标签','Word labels'),L('读标签，找对应物品。','Match introduced words and pictures.'),labels),F(L('生活顺序','First and next'),L('按顺序点图片。','Tap pictured events in order.'),seq))
 words=[O('火 + 车 → 火车',['火','车'],'火和车按这个顺序组成火车。'),O('书 + 包 → 书包',['书','包'],'书和包组成书包。')] if zh else [O('Copy the word: cat',['c','a','t'],'This spells cat. This is print construction, not sound blending.'),O('Copy the word: book',['b','o','o','k'],'Both o tiles are interchangeable. This spells book.')]
 phrases=[Q(L('大球','a big ball'),[dict(A('ball'),scale='large'),dict(A('ball'),scale='small'),A('book')],explain=L('这颗球比另一颗大。','This ball is larger than the other ball.')),Q(L('桌子下面的球','a ball under the table'),[A('under'),A('on'),A('out')],explain=L('球在桌子下面。','The ball is under the table.'))]
 relations=[Q(L('小猫追小狗。谁在追？','The cat chases the dog. Who is chasing?'),[A('cat'),A('dog'),A('bird')],explain=L('小猫在追小狗。','The cat is the one chasing.')),Q(L('小狗追小猫。谁在追？','The dog chases the cat. Who is chasing?'),[A('dog'),A('cat'),A('bird')],explain=L('小狗在追小猫。','The dog is the one chasing.'))]
 put(lang,3,F(L('组合词语','Build a printed word'),L('按示例组合，不考听音。','Copy/build familiar print; not a silent phonics test.'),words),F(L('读短语','Phrase pictures'),L('理解大小、位置。','Understand size and position.'),phrases),F(L('谁做什么','Who does what?'),L('词语顺序改变意思。','The relationship changes when the subject changes.'),relations))
 meaning=[Q(L('球在桌子上面。','The ball is on the table.'),[A('on'),A('under'),A('in')],explain=L('球在桌面上。','The ball is above the tabletop.')),Q(L('球在盒子里面。','The ball is in the box.'),[A('in'),A('out'),A('under')],explain=L('球在盒子内。','The ball is inside the box.'))]
 sentence=[O(L('排列句子：谁 / 做什么 / 吃什么','Build a sentence: who / action'),['小兔','吃','胡萝卜'] if zh else ['The rabbit','eats','a carrot'],L('小兔吃胡萝卜。','The rabbit eats a carrot.')),O(L('排列句子：谁 / 做什么','Build a sentence: who / action'),['小狗','跑步'] if zh else ['The dog','runs'],L('小狗跑步。','The dog runs.'))]
 fill=[Q(L('小兔口渴了，要喝____。','Rabbit is thirsty. Rabbit drinks ____.'),[L('水','water'),L('书','a book'),L('鞋','a shoe')],explain=L('喝水可以解渴。','Water is a drink.')),Q(L('下雨了，小熊带上____。','It is raining. Which item does Bear take?'),[L('雨伞','umbrella'),L('枕头','pillow'),L('书包','empty bag')],explain=L('雨伞可以挡雨。','An umbrella helps keep rain off.'))]
 put(lang,4,F(L('读句子选图','Sentence pictures'),L('读懂位置和动作。','Read actions and positions.'),meaning),F(L('排列句子','Sentence order'),L('点击词块，撤销可修改。','Tap word chunks; Undo changes the order.'),sentence),F(L('补上词语','Complete the meaning'),L('根据情境选择词。','Use context to choose a word.'),fill))
 story1=L('小兔带了一本书到公园。下雨了。小兔把书放进包里，然后跑到屋里。书没有淋湿。','Rabbit took a book to the park. Rain began. Rabbit put the book in a bag and went inside. The book stayed dry.')
 story2=L('小猫在桌边看书。小狗拿来一杯水，放在桌上。小猫说谢谢，小狗笑了。','Cat was reading at the table. Dog brought a cup of water and put it on the table. Cat said thank you. Dog smiled.')
 sequence=[O(story1+'\n'+L('按故事顺序排列。','Order the events in the story.'),[L('带书到公园','Take a book to the park'),L('下雨','Rain begins'),L('把书放进包里','Put the book in a bag'),L('走进屋里','Go inside')],L('这和故事发生的顺序一致。','The order matches the passage.')),O(story2+'\n'+L('按故事顺序排列。','Order the events in the story.'),[L('小猫看书','Cat reads'),L('小狗拿水','Dog brings water'),L('小猫道谢','Cat says thank you')],L('这和故事发生的顺序一致。','The order matches the passage.'))]
 cause=[Q(story1+'\n'+L('小兔为什么进屋？','Why did Rabbit go inside?'),[L('下雨了','Rain began'),L('书丢了','The book was lost'),L('天黑了','It became dark')],explain=L('故事说下雨了，小兔随后进屋。','The passage says rain began before Rabbit went inside.')),Q(story2+'\n'+L('小猫为什么说谢谢？','Why did Cat say thank you?'),[L('小狗拿来了水','Dog brought water'),L('小狗藏了书','Dog hid the book'),L('小狗关了门','Dog closed the door')],explain=L('小狗给小猫拿来了水。','Dog brought water to Cat.') )]
 refs=[Q(L('小兔找到了小熊。他把钥匙递给小兔。这里的“他”是谁？','Rabbit found Bear. Bear had a key. He handed it to Rabbit. Who is “he”?'),[L('小熊','Bear'),L('小兔','Rabbit'),L('小猫','Cat')],explain=L('小熊把自己拿着的钥匙递给小兔。','Bear held the key and handed it to Rabbit.')),Q(L('小猫看见小狗拿着书。小狗说：“这是我的书。”谁的书？','Cat saw Dog holding a book. Dog said, “This is my book.” Whose book is it?'),[L('小狗','Dog'),L('小猫','Cat'),L('小兔','Rabbit')],explain=L('说“我的书”的是小狗。','Dog is the speaker of “my book.”'))]
 if zh:refs[0]['prompt']='小熊拿着钥匙，小兔走过来。小熊说：“我把钥匙给你。”谁拿着钥匙？';refs[0]['explain']='开头明确说小熊拿着钥匙。'
 put(lang,5,F(L('故事顺序','Story sequence'),L('联系几句话中的事件。','Connect events across the passage.'),sequence),F(L('原因和结果','Cause in the story'),L('找故事写出的原因。','Find the reason stated by the text.'),cause),F(L('指的是谁','Who is meant?'),L('联系说话的人和代词。','Connect speakers and references.'),refs))
 inference=[S(Q(story1+'\n'+L('书为什么可能没淋湿？','Why did the book probably stay dry?'),[L('小兔把书放进包里','Rabbit put it in a bag'),L('书从来不怕水','Books cannot get wet'),L('没有下雨','There was no rain')]),Q(L('哪条信息支持这个解释？','Which detail supports that explanation?'),[L('下雨后，小兔把书放进包里','Rabbit put the book in a bag after rain began'),L('小兔喜欢公园','Rabbit likes the park'),L('书很有趣','The book is interesting')],explain=L('放进包里的动作支持这个解释；它是推断，不是实验结论。','The action supports the inference; it is not an experimental proof.'))),S(Q(story2+'\n'+L('小狗为什么可能笑了？','Why might Dog have smiled?'),[L('得到感谢，可能很开心','Dog may have felt happy after being thanked'),L('小猫一定在嘲笑他','Cat must have mocked Dog'),L('水杯一定坏了','The cup must have broken')]),Q(L('哪条信息支持这个猜想？','Which detail supports that possibility?'),[L('小猫说了谢谢','Cat said thank you'),L('桌子很大','The table was big'),L('门开着','The door was open')],explain=L('道谢是线索，但不能确定小狗的全部想法。','The thanks is a clue, not certainty about all of Dog’s feelings.')))]
 ending=[Q(story1+'\n'+L('哪个结尾与故事一致？','Which ending is consistent?'),[L('小兔在屋里拿出干燥的书','Rabbit takes the dry book out indoors'),L('小兔从没去公园','Rabbit never went to the park'),L('小兔找到了丢失的雨伞','Rabbit finds a lost umbrella')],explain=L('屋里和干燥的书都与故事一致，另外两个添加或否定了信息。','The indoor setting and dry book follow the stated events.')),Q(story2+'\n'+L('哪个结尾保持人物行为一致？','Which ending keeps the details consistent?'),[L('小猫喝了小狗拿来的水','Cat drinks the water Dog brought'),L('小狗从没拿水','Dog never brought water'),L('小猫把鞋放到杯子里','Cat puts shoes in the cup')],explain=L('这个结尾延续了拿水的情节。','This continues the water-delivery scene.'))]
 edit=[Q(L('小猫和小狗站在门边。他打开门。怎样写才清楚是谁开门？','Cat and Dog stood by the door. He opened it. Which revision clearly names the opener?'),[L('小狗打开门','Dog opened the door'),L('他打开门','He opened it'),L('门在那边','The door was there')],explain=L('直接写名字可以消除指代不清。','Naming Dog makes the referent explicit.')),Q(L('原句：小兔把书放进包里，书没有淋湿。哪句保留原意？','Rabbit put the book in a bag, and it stayed dry. Which sentence keeps that meaning?'),[L('包里的书没有淋湿','The book in the bag stayed dry'),L('书被雨淋湿了','The book got wet'),L('小兔把书扔掉了','Rabbit threw the book away')],explain=L('保留了书的位置和干燥的结果。','The location and dry outcome are preserved.'))]
 put(lang,6,F(L('推断和证据','Inference and evidence'),L('先推断，再选支持线索。','Infer, then identify supporting evidence.'),inference),F(L('合适的结尾','A consistent ending'),L('结尾要和前文一致。','Keep an ending consistent with the passage.'),ending),F(L('把话说清楚','Clearer sentences'),L('改掉指代或意思不清。','Revise references without changing meaning.'),edit))
 if zh:
  for lev in D[lang]['levels']:
   for fam in lev['families']:
    for task in fam['tasks']:
     for st in task.get('stages',[task]):
      if st.get('cue')=='Choose the answer.':st['cue']='看清提示，选择答案。'
      if st.get('mode')=='order':st['cue']='按顺序点词卡或图片。↶ 可以撤销。'
      st['retry']='再看看提示，试一试。'
subject('science','Everyday Science','Observe, predict and use evidence. Pictures and supplied records are learning models, not real experiments.','For preschoolers, narrate and connect pictures to real observations. Predictions can change. These original scenarios use stated evidence; no universal material rule is implied.',[
 ('Observe','Notice parts and visible details'),('Compare','Group observations and order changes'),('Predict','Link a condition with a possible result'),('Use evidence','Separate observation from prediction'),('Investigate','Compare fairly and interpret records'),('Explain limits','Consider alternatives and a useful next test')],['leaf on plant','seed → sprout','predict → observe','observation or guess?','change one factor','evidence → next test'])
put('science',1,
 F('Plant parts','Find the visible part.',[Q('Find the leaf.',[A('leaf'),A('seed'),A('cup')],explain='The leaf is the broad flat plant part.',scene=[A('plant')]),Q('Find the seed.',[A('seed'),A('book'),A('shoe')],explain='This pictured seed can be planted.')]),
 F('Everyday uses','Connect an object to an observed use.',[Q('Which pictured object holds water for drinking?',[A('cup'),A('key'),A('sock')],explain='The pictured cup can hold drinking water.'),Q('Which pictured object can shelter you from falling rain?',[A('umbrella'),A('book'),A('shoe')],explain='The umbrella covers an area above you.',scene=[A('rain')])]),
 F('Notice the scene','Describe what is pictured.',[Q('Which picture shows drops of water?',[A('water'),A('sun'),A('book')],explain='The water-drop picture shows the stated detail.'),Q('Which picture shows a plant with leaves?',[A('plant'),A('seed'),A('ball')],explain='Leaves are visible on this plant.')]))
put('science',2,
 F('Compare visible features','Use the displayed category.',[M('Select every striped outline.',[feat('circle','striped'),feat('square'),feat('triangle','striped')],[0,2],'Both selected drawings have visible stripes.'),M('Select every round outline.',[feat('circle'),feat('circle','filled'),feat('square')],[0,1],'Both selected drawings have round outlines.')]),
 F('Weather preparation','Use the supplied conditions.',[Q('Heavy rain is falling. Which item helps keep your head dry?',[A('umbrella'),A('book'),A('cup')],explain='An open umbrella can shelter your head.'),Q('This toy scene has a wet puddle. Which item is made for feet?',[A('shoe'),A('cup'),A('key')],explain='Footwear covers feet; real puddle footwear should suit the conditions.')]),
 F('A growing plant','Follow this shown growth sequence.',[O('This seed grows: first → last',[A('seed'),A('sprout'),A('plant')],'The pictured sequence goes from seed to sprout to a larger plant.'),O('Picture records: yesterday → today → later',['Seed in soil','A small sprout appears','The pictured sprout has more leaves'],'These records describe one plant over time.')]))

def P(prompt,opts,observation,question,answers,explain):
 a=Q(prompt,opts,explain='',cue='Choose a prediction. It is a guess to check, not a scored answer.');a['mode']='predict';a['observation']=observation
 return S(a,Q('Observed result: '+observation+'\n'+question,answers,explain=explain,cue='Use the observed result to choose an explanation.'))
put('science',3,
 F('Predict and observe','A prediction can be revised.',[P('A toy ball is released on a ramp whose left side is higher. Which way might it roll?',['Toward the lower right','Toward the higher left'],'In this trial, the ball rolled to the lower right.','Which statement matches this trial?',['The ball rolled downhill in this trial','All objects always roll right','The ball moved uphill'],'The observation supports downhill motion in this trial.'),P('A paper towel and a plastic lid each receive a drop of water. Which might absorb the drop?',['The paper towel','The plastic lid'],'The drop soaked into the towel; it stayed on the lid.','Which statement matches the observation?',['The towel absorbed water in this trial','Every paper object absorbs equally','The lid absorbed the drop'],'The supplied trial shows water absorption by this towel.')]),
 F('Conditions matter','Read the provided plant observations.',[Q('Two seedlings of the same kind received equal light. A received water; B did not. After a week, A stayed upright and B wilted. What difference was recorded?',['A stayed upright; B wilted','Both stayed upright','Both grew flowers'],explain='This describes the recorded difference; it does not prove every plant needs the same amount of water.'),Q('Two pictured leaves were observed: A has a smooth edge; B has a jagged edge. Which claim is supported?',['Their edges differ','A is definitely healthier','B must be older'],explain='The edge description supports a visible difference, not health or age.')]),
 F('Compare records','Keep your explanation tied to the data.',[Q('Trial A: ball traveled to the end of the ramp. Trial B: ball stopped halfway. What did we observe?',['Different stopping places','The balls have the same weight','The ramp caused all differences'],explain='Only stopping positions are recorded.'),Q('Morning record: puddle covers the whole chalk circle. Afternoon: it covers half. What changed?',['The visible wet area became smaller','The puddle became deeper','The water turned into soil'],explain='The pictures show a smaller wet area; depth was not recorded.')]))
put('science',4,
 F('Observation or prediction?','Describe what is seen versus what might happen.',[Q('Which is an observation?',['This leaf has three holes','This leaf may get more holes tomorrow','An insect will visit tomorrow'],explain='The holes are observed now. The other statements predict future events.'),Q('Which is a prediction?',['This ball may roll farther on a steeper ramp','This ramp has a rough surface','The ball stopped at this line'],explain='May roll farther describes a result to test, not one already observed.')]),
 F('Read an evidence record','Use every stated record.',[Q('Seedling records: A has 2 leaves on Monday and 4 on Friday. B has 2 on both days. Which changed?',['A gained leaves; B did not','Both gained leaves','B gained more leaves'],explain='Compare each seedling’s first and last record.'),Q('Two trials: a wooden block floated; a metal spoon sank. Which statement reports the trials without overgeneralizing?',['This block floated and this spoon sank','All wood always floats','All metal always sinks'],explain='The observations concern these objects and conditions, not every material shape.')]),
 F('A question we can test','Choose a question answered by the setup.',[Q('We can release the same ball on two ramp heights. Which question can this setup test?',['Does ramp height change the stopping distance?','Which ramp looks happiest?','Do all animals like ramps?'],explain='The setup can compare a recorded distance at two heights.'),Q('We can give equal-sized paper samples one equal drop each. Which question can we investigate?',['Which sample absorbs the drop first?','Which paper is the best in every way?','Who invented all paper?'],explain='The investigation can measure this defined absorption outcome.')]))
put('science',5,
 F('Compare fairly','Change the factor you intend to test.',[Q('Question: does water affect these seedlings? Setup A is sunny and watered; B is dark and dry. What should change in the plan?',['Give both equal light; vary water only','Change soil and pot too','Use different plant kinds'],explain='Keeping light and other conditions alike helps isolate watering.'),Q('Question: does ramp surface affect travel? Two trials use different balls AND surfaces. What is a better comparison?',['Use the same ball; change only the surface','Change height and ball too','Use only one surface'],explain='The same ball reduces a competing explanation.')]),
 F('Evidence and conclusion','Avoid stronger claims than the records allow.',[Q('Three trials with the same ball: steep ramp distances 40, 42, 41; shallow ramp distances 20, 21, 19. Which claim fits?',['The ball traveled farther on the steep ramp in these trials','Every object always doubles its distance','Ramp angle is irrelevant'],explain='The recorded steep-ramp distances are consistently larger in these trials.'),Q('Three towel samples absorbed equal drops in 5, 6 and 5 seconds; three lid samples did not absorb within the observation period. Which conclusion fits?',['These towels absorbed the drops during the observed period','All towels absorb any liquid instantly','Lids never interact with water'],explain='The conclusion stays within the objects, liquid and observed period.')]),
 F('Revise a prediction','Choose a response to unexpected evidence.',[P('You think the large toy block will sink. What is your prediction?',['It will sink','It will float'],'The hollow block floated in all three trials.','How should we respond?',['Revise the prediction; inspect shape and hollow space','Ignore the three observations','Say that size alone determines sinking'],'Repeated observations can lead us to revise a prediction.'),P('You think both ramps will give the same stopping distance. What is your prediction?',['Same distance','Different distances'],'On the rough ramp the ball stopped sooner in three trials.','What should we do next?',['Record the difference and test again under matched conditions','Erase the rough-ramp results','Claim all rough surfaces stop every object'],'A revised hypothesis and a fair repeat are useful next steps.')]))
put('science',6,
 F('Competing explanations','Two changed factors can leave uncertainty.',[Q('A plant in light with water grew; a plant in darkness without water did not. What can we conclude about light alone?',['This comparison cannot isolate light from water','Light alone certainly caused everything','Water certainly had no role'],explain='Both light and water changed, leaving competing explanations.'),Q('A large hollow block floated; a small solid ball sank. Which explains the result by size alone?',['The evidence is insufficient for a size-only rule','All large objects float','All small objects sink'],explain='Shape, material and hollow space also differ; size alone is not isolated.')]),
 F('Choose the next investigation','Choose evidence that separates explanations.',[Q('Two seedling trials differed in both soil and light. We want to test light. Choose the next comparison.',['Same soil and watering; vary light','Different soil, water and light','Same light; vary soil only'],explain='Changing light while matching other conditions addresses the light hypothesis.'),Q('A ball traveled farther on a high smooth ramp than a low rough ramp. We want to test surface. Choose the next comparison.',['Same ball and height; vary surface','Vary ball, height and surface','Change only the room decoration'],explain='A controlled surface comparison separates surface from height.')]),
 F('Explain with limits','An explanation needs evidence and boundaries.',[S(Q('A class observed four wet patches shrink outdoors in the sun. Choose a supported statement.',['Their visible wet areas shrank during observation','Water can only disappear in sunlight','All patches shrink at the same speed']),Q('Which qualification matters?',['We did not compare shade or measure all conditions','We know every possible weather condition','Four patches prove every water rule'],explain='The observation does not isolate sunlight or establish a universal rate.')),S(Q('Three magnets attracted the tested steel clips but not the wooden blocks. Choose a supported statement.',['The tested clips were attracted; the tested blocks were not','All metal is magnetic','Magnets attract every shiny thing']),Q('What would improve the next investigation?',['Test specified objects made of other materials','Choose only objects that already fit the guess','Ignore trials with no attraction'],explain='More specified material tests probe the rule; shine alone is not a material property.'))]))

subject('stories','Stories & Feelings','Original stories with several possible helpful paths. A grown-up may narrate. Feelings are not right or wrong.','Ask what the character might need and what else could help. Respect boundaries. An emotion guess is a possibility, not a diagnosis. Story paths do not produce behavior scores.',[
 ('Notice','Notice an event and possible feelings'),('Respond','Link events, needs and help'),('Understand others','Consider two viewpoints and boundaries'),('Explore choices','Compare actions and possible consequences'),('Resolve','Plan for several needs'),('Consider possibilities','Handle uncertainty and tradeoffs')],['event → feeling','need → help','my view + your view','choice → consequence','two needs → plan','possible reason → question'])

def B(text,art,choices):
 global serial;serial+=1
 nodes={'start':{'text':text,'art':art,'options':[]}}
 for i,(label,result) in enumerate(choices):
  node='end'+str(i);nodes['start']['options'].append({'text':label,'to':node});nodes[node]={'text':result,'end':True}
 return {'id':'story-'+str(serial),'mode':'branch','nodes':nodes,'guide':'Explore one possible path, then try another. More than one choice may be helpful. No feeling is scored as wrong.'}

def B2(text,art,first,second):
 q=B(text,art,first)
 for i,node in enumerate([n for n in q['nodes'] if n!='start']):
  outcome=q['nodes'][node]['text'];q['nodes'][node]={'text':outcome,'cue':'What could help next?','options':[]}
  for j,(label,result) in enumerate(second):
   end=node+'-'+str(j);q['nodes'][node]['options'].append({'text':label,'to':end});q['nodes'][end]={'text':result,'end':True}
 return q
put('stories',1,
 F('What happened?','Notice one story detail.',[Q('Rabbit dropped a book while walking. What fell?',[A('book'),A('cup'),A('shoe')],explain='The story says the book fell.'),Q('Bear brought a cup to Rabbit. What did Bear bring?',[A('cup'),A('key'),A('umbrella')],explain='The story names the cup.')]),
 F('Possible feelings','Different feelings can make sense.',[B('Rabbit cannot find a favorite toy. What might Rabbit feel?','rabbit0',[('Sad','Rabbit might feel sad about missing the toy.'),('Worried','Rabbit might worry about where the toy is.'),('Not sure','We can ask Rabbit; a picture does not tell us everything.')]),B('Bear sees a new playground. What might Bear feel?','bear0',[('Excited','Bear might feel excited to explore.'),('Unsure','Bear might feel unsure about a new place.'),('Both','Excitement and uncertainty can happen together.')])]),
 F('Offer comfort','Explore a gentle response.',[B('Rabbit is upset after a tower falls. What could help?','blocks',[('Sit nearby','Staying nearby can offer company without demanding a hug.'),('Ask if help is wanted','Rabbit can choose whether rebuilding help is wanted.')]),B('Bear is tired after play. What could help?','bear0',[('Offer a quiet place','A quieter place may help Bear rest.'),('Ask what Bear needs','Bear can tell us or show us what might help.')])]))
put('stories',2,
 F('Story order','Follow the events that are stated.',[O('Rabbit dropped a toy. Bear noticed it. Bear returned it. Put those events in order.',['Rabbit drops the toy','Bear notices the toy','Bear returns the toy'],'This matches the stated story.'),O('Bear asked for water. Rabbit brought a cup. Bear drank. Put the events in order.',['Bear asks','Rabbit brings water','Bear drinks'],'This matches the stated story.')]),
 F('Ask for help','Choose a possible way to get support.',[B('Rabbit cannot reach a book on a high shelf.','book',[('Ask a trusted grown-up','A grown-up can help retrieve the book safely.'),('Choose another reachable book','Rabbit can choose a reachable book while waiting for help.')]),B('Bear cannot find the classroom door.','door',[('Ask the teacher','A familiar teacher can guide Bear.'),('Stay with a trusted grown-up','Bear can stay nearby while asking for directions.')])]),
 F('What might be needed?','A scene suggests a need, not certainty.',[B('After running, Rabbit says “I am thirsty.”','run',[('Offer water','Rabbit has stated a need for a drink.'),('Ask where to get water','Finding drinking water can help.')]),B('Music is loud. Bear says “My ears need a break.”','music',[('Move to a quieter place','A quieter place may meet the stated need.'),('Ask to lower the volume','A request can help change the shared space.')])]))
put('stories',3,
 F('Two viewpoints','Notice that two people can need different things.',[Q('Rabbit wants to finish a tower. Bear wants a turn with the blocks. Which statement recognizes both?',['Rabbit wants to finish; Bear wants a turn','Only Rabbit matters','Bear must not want to play'],explain='Both stated wishes can be recognized.'),Q('Bear wants quiet; Rabbit wants music. Which statement fits?',['Both have a stated preference','One must be a bad friend','Both must want music'],explain='Different preferences do not make someone bad.')]),
 F('Say a boundary','Being kind can include saying no.',[B('Rabbit is using the train. Bear reaches for it.','engine',[('I am using it. You can ask for a turn.','Rabbit states a boundary and offers a way to talk.'),('Ask a grown-up to help arrange turns','Help is a valid option if arranging turns is difficult.')]),B('Bear does not want a hug.','bear0',[('No hug, thank you.','Bear can decline physical affection.'),('Offer a wave instead','A wave is an optional alternative; Bear can still decline.')])]),
 F('Repair a mistake','Choose a way to acknowledge and help.',[B('Rabbit accidentally knocks Bear’s blocks down.','blocks',[('Say what happened and offer help','Acknowledging the accident and offering help can support repair.'),('Ask if Bear wants space first','Bear may want space before rebuilding.')]),B('Bear spills water near Rabbit’s book.','cup',[('Tell Rabbit and ask a grown-up for a towel','Prompt help can protect the book and clean the spill.'),('Move the book away with permission','Protecting the book can be useful while getting help.')])]))
put('stories',4,
 F('Explore consequences','A consequence is a possibility, not a punishment.',[B2('Rabbit and Bear both want the train. Choose a path.','engine',[('Ask for a turn','Bear hears a request; a turn plan is possible.'),('Grab the train','Bear may feel upset; grabbing can hurt or start a conflict.')],[('Talk about a turn plan','They can agree on a plan with adult help if needed.'),('Ask for help','A trusted grown-up can help them keep everyone safe.')]),B2('Bear is angry because a tower fell.','blocks',[('Take a pause','A pause may help Bear decide what to do.'),('Throw a block','A thrown block could hurt someone; anger does not require throwing.')],[('Put the block down and ask for help','Putting it down supports safety while Bear gets help.'),('Move to a safe quiet spot','Bear can take space and return when ready.')])]),
 F('Feeling and action','A feeling is allowed; actions have effects.',[Q('Bear feels angry. Which statement separates a feeling from an action?',['Feeling angry is okay; hitting can hurt','Anger makes hitting required','Bear must never feel angry'],explain='Feelings can be accepted while safer actions are chosen.'),Q('Rabbit feels nervous about joining a game. Which statement helps?',['Rabbit may watch first or ask to join','Rabbit must join immediately','Nervous feelings are wrong'],explain='Watching and asking are both possible choices.')]),
 F('A helpful plan','Try a response without forced sharing or affection.',[B('Rabbit wants to keep using a favorite toy for now.','engine',[('Explain and arrange a later turn','A clear boundary and later turn can be reasonable.'),('Ask for help deciding a plan','An adult can help when needs conflict.')]),B('Bear is upset and does not want to talk yet.','quiet',[('Offer space and stay available','Space can be offered without abandoning support.'),('Ask whether sitting nearby would help','Bear can choose whether company is wanted.')])]))
put('stories',5,
 F('Meet two needs','Explore workable compromises.',[B2('Rabbit wants music. Bear needs quiet to read in their shared room.','music',[('Move music to another room','Separating spaces may meet both needs.'),('Agree on quiet and music times','A shared schedule may help if both agree.')],[('Check whether both are comfortable','Checking both needs makes the plan more useful.'),('Ask a grown-up for another option','Support can help when the first plan does not work.')]),B2('Rabbit needs the table for a puzzle. Bear needs it for drawing.','blocks',[('Use different parts of a large enough table','Separate space may allow both activities.'),('Agree on turns','Turns can work if the waiting time is manageable.')],[('Check whether the plan works for both','A plan can be revised after hearing both responses.'),('Look for another work surface with help','Another space may solve the shared-resource problem.')])]),
 F('Intent and impact','An accident can still need repair.',[Q('Bear bumped Rabbit by accident. Rabbit was hurt. Which statement recognizes intent and impact?',['It was accidental, and Rabbit still needs care','An accident means nobody was hurt','Bear must have intended to hurt Rabbit'],explain='Intent and impact are different; care and repair can still be needed.'),Q('Rabbit meant to help but moved Bear’s unfinished picture. Which statement fits?',['Rabbit wanted to help, but Bear may dislike the change','Good intentions guarantee no harm','Bear cannot feel upset'],explain='The effect can differ from the intention.')]),
 F('A safe help-seeking plan','Steps can include boundaries and trusted adults.',[O('In this story, Rabbit first moves away from unsafe pushing, then tells a trusted teacher, then explains what happened. Order the stated plan.',['Move to a safer spot','Tell a trusted teacher','Explain what happened'],'This is one possible help-seeking plan, not a requirement to handle pushing alone.'),O('Bear notices a spill, keeps away from the slippery spot, tells an adult, then helps only if asked. Order this story.',['Keep away from the spill','Tell an adult','Help if asked'],'The story puts safety and adult help before cleanup.')]))
put('stories',6,
 F('Unknown intentions','Choose a question rather than mind-reading.',[B('Bear did not answer Rabbit’s greeting. We do not know why.','bear0',[('Maybe Bear did not hear; ask gently','Not hearing is one possibility, not a fact.'),('Maybe Bear needs space; check later','Needing space is another possibility.'),('We need more information','We cannot know Bear’s intention from this event alone.')]),B('Rabbit left a game early without explaining.','rabbit0',[('Ask whether Rabbit needed something','A question can gather information.'),('Consider that Rabbit might be tired','Tiredness is possible, but not certain.'),('Do not decide the reason yet','Waiting for information avoids assuming bad intent.')])]),
 F('Compare reasonable plans','Tradeoffs can change which plan fits.',[S(Q('Bear needs quiet now; Rabbit wants music now. A spare room is available. Which plan can meet both immediate needs?',['Use separate rooms for now','Force Bear to listen','Force Rabbit to stop all music forever']),Q('Why might this plan help?',['The available separate space can support both needs','Bear’s preference is always more important','Friends must want the same things'],explain='This plan fits the stated available space; another context might need another plan.')),S(Q('One toy train is available. Rabbit is finishing a short track and Bear wants a turn. Which plan could respect both?',['Agree on a later turn and check that the wait works','Declare Bear can never use it','Grab it immediately']),Q('What should they check?',['Whether the turn plan works for both','Who is the better child','Whether they have identical feelings'],explain='A workable agreement can be checked and revised.'))]),
 F('Ask, then revise','New information can change a response.',[B2('Bear looks upset after a game. Rabbit does not know why.','sad',[('Ask what happened','Bear says the rules were confusing.'),('Ask whether help or space is wanted','Bear says help understanding the rules would be useful.')],[('Go over the rules together','They can clarify the rules and decide whether to continue.'),('Ask a trusted grown-up to explain','A grown-up can help with confusing rules.')]),B2('Rabbit is standing outside a group game. Bear is unsure whether Rabbit wants to join.','rabbit0',[('Ask if Rabbit wants to join','Rabbit says watching first feels better.'),('Offer information about the game','Rabbit says knowing the rules helps, but watching first is preferred.')],[('Respect watching first','Rabbit can watch and decide later.'),('Stay available for questions','Support can remain available without forcing participation.')])]))
# Every displayed sample has a stable identity; no runtime language stitching.
(R/'learning/content.json').write_text(json.dumps(D,ensure_ascii=False,indent=2))
print('Authored:',{s:sum(len(f['tasks']) for l in c['levels'] for f in l['families']) for s,c in D.items()})
