"""Original variation packs. Variants change clues/events/relationships, never only names."""
from itertools import permutations,product

def expand(D,Q,A,O,S,B,B2,M,feat):
 def bank(s,l,f):return D[s]['levels'][l-1]['families'][f]['tasks']
 def add(s,l,f,qs):bank(s,l,f).extend(qs)
 def replace(s,l,f,qs):D[s]['levels'][l-1]['families'][f]['tasks']=qs
 shapes=['circle','square','triangle'];fills=['plain','striped','filled']
 # Visual content changes, not choice-position permutations.
 replace('logic',1,0,[Q('＝ → ?',[feat(sh,fi,z),feat(shapes[(shapes.index(sh)+1)%3],fi,z),feat(sh,fills[(fills.index(fi)+1)%3],z)],scene=[feat(sh,fi,z)],cue='Find the same picture.',explain='Both the outline and pattern match.') for sh,fi,z in product(shapes,fills,['small','large'])])
 replace('logic',1,1,[Q('Find the changed pattern.',[feat(sh,to),feat(sh,fr),feat(shapes[(shapes.index(sh)+1)%3],fr)],scene=[feat(sh,fr)],cue='Same outline, different pattern.',explain='The outline stays the same; its pattern changes.') for sh in shapes for fr in fills for to in fills if fr!=to])
 replace('logic',1,2,[Q('Part → whole',[feat(sh,fi),feat(shapes[(shapes.index(sh)+1)%3],fi),feat(sh,fills[(fills.index(fi)+1)%3])],scene=[dict(feat(sh,fi),crop=64)],cue='Find the whole picture.',explain='The visible outline and pattern match the whole.') for sh,fi in product(shapes,fills)]+[Q('Part → whole',[A(a),A(b),A(c)],scene=[dict(A(a),crop=72)],cue='Find the whole picture.',explain='The visible part belongs to this object.') for a,b,c in [('book','cup','shoe'),('key','book','door'),('engine','boat','bus')]])
 uses=[('Enter a room through its opening','key','door'),('Keep feet covered','sock','shoe'),('Keep rain off','rain','umbrella'),('Hold drinking water','water','cup'),('Read a story','book','book'),('Rest on a bed','sleep','bed'),('Dry wet hands','wash','dry'),('Water a seedling','plant','water'),('Travel on rails','engine','engine'),('Carry people on a road','bus','bus'),('Cross water in a vessel','water','boat'),('Listen to a tune','music','music')]
 replace('logic',2,0,[Q(p+' → choose the useful object',[A(correct),A('book' if correct!='book' else 'shoe'),A('key' if correct!='key' else 'ball')],scene=[A(clue)],explain='The chosen object fits the stated use.') for p,clue,correct in uses])
 # One explicit feature only at level 2; varied positive and negative examples.
 rules=[]
 for sh,fi in product(shapes,fills):
  opts=[feat(sh,fi),feat(shapes[(shapes.index(sh)+1)%3],fi),feat(sh,fills[(fills.index(fi)+1)%3])]
  rules.append(M(fi.capitalize()+' pattern only',opts,[0,1],'Both selected pictures have the stated pattern.',[feat(sh,fi)]))
 for sh in shapes:rules.append(M('Outline only: '+sh,[feat(sh),feat(sh,'striped'),feat(shapes[(shapes.index(sh)+1)%3])],[0,1],'Both selected pictures have the stated outline.',[feat(sh)]))
 replace('logic',2,1,rules)
 routines=[('Hands: wash, then dry',['wash','dry']),('Feet: socks, then shoes',['sock','shoe']),('Growing: seed, then sprout',['seed','sprout']),('Growing: sprout, then plant',['sprout','plant']),('In this story: rain, then sun',['rain','sun']),('In this story: run, then rest',['run','bed']),('Unlocking story: key, then door',['key','door']),('In this story: eat, then sleep',['eat','sleep']),('In this story: book, then bed',['book','bed']),('In this story: rain, then umbrella',['rain','umbrella']),('In this story: music, then quiet',['music','quiet']),('In this story: wash, then eat',['wash','eat'])]
 replace('logic',2,2,[O(p+' — put these pictured steps in that order.',[A(a) for a in items],'This follows the stated order.') for p,items in routines])
 replace('logic',3,0,[Q(sh+' AND '+fi,[feat(sh,fi,z),feat(sh,fills[(fills.index(fi)+1)%3],z),feat(shapes[(shapes.index(sh)+1)%3],fi,z)],scene=[feat(sh,'plain',z),feat(shapes[(shapes.index(sh)+1)%3],fi,z)],explain='The answer meets both features.') for sh,fi,z in product(shapes,fills,['small','large'])])
 replace('logic',3,1,[Q('Same change → ?',[feat(target,to),feat(target,fr),feat(source,to)],scene=[feat(source,fr),feat(source,to),feat(target,fr)],explain='Keep the outline; apply the demonstrated pattern change.') for source,target in permutations(shapes,2) for fr,to in permutations(fills,2)])
 patterns=[]
 for a,b in permutations(shapes,2):
  for repeat in [1,2]:
   seq=[a]*repeat+[b]+[a]*repeat+[b]+[a]*repeat
   patterns.append(Q('Follow the repeating picture rule.',[feat(b),feat(a),feat(next(s for s in shapes if s not in [a,b]))],scene=[feat(v) for v in seq],explain='The displayed group repeats; the next picture closes that group.'))
 replace('logic',3,2,patterns)
 replace('logic',4,0,[Q(sh+' outline AND NOT '+no,[feat(sh,yes),feat(sh,no),feat(other,yes)],explain='Only one picture meets both clues.') for sh,other in permutations(shapes,2) for no,yes in [('filled','plain'),('plain','striped')]])
 objects=['book','cup','key','door','ball','shoe']
 for l,f in [(4,1),(5,0),(5,1),(6,2)]:
  qs=[]
  for i,triple in enumerate(list(permutations(objects,3))[:24]):
   a,b,c=triple
   if l==4:p=a+' before '+b+'. '+b+' before '+c+'.';edges=[[0,1],[1,2]]
   elif f==0:p='Left → right: '+b+' is in the middle. '+a+' is left of '+b+'. '+c+' is right of '+b+'.';edges=[[0,1],[1,2]]
   else:
    fork=i%2==0;edges=[[0,1],[0,2]] if fork else [[0,2],[1,2]]
    p=(a+' before both '+b+' and '+c+'. Those two may be in either order.') if fork else (c+' after both '+a+' and '+b+'. Those two may be in either order.')
   first=O(p,[A(a),A(b),A(c)],'All stated dependencies are satisfied.',edges)
   if l==6:first=S(first,Q('Why is the plan valid?',[p,'The first pictured object always has to go last','Object size determines the order'],explain='The plan satisfies the two stated dependencies.'))
   qs.append(first)
  replace('logic',l,f,qs)
 clue_objects=[('Has wheels AND travels on rails','engine','bus','boat'),('Has pages AND is used for reading','book','door','cup'),('Has a handle AND holds a drink','cup','ball','book'),('Has a canopy AND helps keep rain off','umbrella','book','door'),('Fits a lock AND has a toothed shaft','key','shoe','cup'),('Is a plant part AND has veins on a flat blade','leaf','flower','water'),('Has fins AND swims','fish','bird','cat'),('Has feathers AND a beak','bird','fish','dog'),('Is an animal AND has the pictured pointed ears','cat','dog','fish'),('Has a sole AND is worn on feet','shoe','sock','book'),('Has a stem AND petals','flower','root','fruit'),('Has branches below the soil AND belongs to a plant','root','stem','leaf')]
 replace('logic',4,2,[Q(p+'. Which pictured object meets both clues?',[A(a),A(b),A(c)],explain='The selected object meets both stated clues.') for p,a,b,c in clue_objects])
 replace('logic',5,2,[Q('Plan: '+b+' → '+a+' → '+c+'. Rule: '+a+' before '+b+'; '+b+' before '+c+'.',['Swap the first two objects','Move the last object to the start','Remove the middle object'],explain='The swap restores both required relationships.') for a,b,c in list(permutations(objects,3))[:12]])
 replace('logic',6,0,[Q('Rule: every picture has '+fi+' pattern. Which disproves it?',[feat(sh,other),feat(sh,fi),feat(shapes[(shapes.index(sh)+1)%3],fi)],explain='The selected picture has a different pattern, so the all-rule fails.') for sh in shapes for fi,other in permutations(fills,2)])
 distinctions=[('train','bus','Travel on rails?','Have wheels?','Carry people?'),('cat','dog','Have the pictured pointed ears?','Have eyes?','Be an animal?'),('book','cup','Have pages?','Fit on a table?','Be carried?'),('shoe','sock','Have the pictured sole?','Go on a foot?','Be clothing?'),('rain','sun','Show water drops?','Be weather?','Be outdoors?'),('boat','bus','Travel on water?','Carry people?','Be a vehicle?')]
 replace('logic',6,1,[Q(a+' or '+b+'. Which clue distinguishes these pictures?',[good,w1,w2],explain='This clue separates the two stated candidates.') for a,b,good,w1,w2 in distinctions]+[Q(a+' or '+b+'. We only know: '+shared+' Can we choose?',['Not enough information','It must be '+a,'It must be '+b],explain='Both candidates fit the shared clue; seek a distinguishing detail.') for a,b,shared in [('book','cup','on a table.'),('cat','dog','an animal.'),('train','bus','has wheels.'),('shoe','sock','worn on feet.'),('sun','rain','weather.'),('boat','bus','carries people.')]])

 nouns=[('杯子','cup','cup'),('书','book','book'),('钥匙','key','key'),('小猫','cat','cat'),('小狗','dog','dog'),('火车','train','engine'),('鞋','shoe','shoe'),('袜子','sock','sock'),('雨伞','umbrella','umbrella'),('小鸟','bird','bird'),('鱼','fish','fish'),('球','ball','ball'),('床','bed','bed'),('门','door','door'),('船','boat','boat'),('公交车','bus','bus')]
 actions=[('睡觉','sleep','sleep'),('洗手','wash hands','wash'),('跑步','run','run'),('吃饭','eat','eat'),('擦干','dry','dry'),('等待','wait','wait')]
 # Distinct narrated action contexts; avoid treating changing a character name as a new task.
 action_contexts=[('跑完了，休息一下。','After a run, rest.','sleep'),('天晚了，上床休息。','At bedtime, rest.','sleep'),('手脏了，用水清洗。','Dirty hands need washing.','wash'),('吃饭前先清洗双手。','Wash hands before a meal.','wash'),('在操场上快步跑起来。','Run across the playground.','run'),('沿着跑道向前跑。','Run along the track.','run'),('午饭时间到了，吃午饭。','At lunchtime, eat lunch.','eat'),('坐下吃早餐。','Sit down to eat breakfast.','eat'),('洗完手，用毛巾擦干。','Use a towel to dry washed hands.','dry'),('衣服湿了，把它擦干。','Dry the wet cloth.','dry'),('轮到朋友了，先等一等。','It is a friend’s turn; wait.','wait'),('老师还没到，安全地等待。','Wait safely until the teacher arrives.','wait')]
 contexts=[('口渴了，选喝水用的东西。','Choose something to hold a drink.','cup'),('想看故事，选能读的东西。','Choose something with a story to read.','book'),('锁关着，选开锁用的东西。','Choose something for a matching lock.','key'),('脚冷了，选穿在脚里的东西。','Choose a covering for feet before shoes.','sock'),('要出门走路，选鞋。','Choose footwear for walking outside.','shoe'),('下雨了，选挡雨的东西。','Choose something to keep rain off.','umbrella'),('要睡觉，选休息的地方。','Choose a place to sleep.','bed'),('想踢着玩，选球。','Choose something to kick in a ball game.','ball'),('要进房间，选门。','Choose the entrance to a room.','door'),('想坐车去另一条街，选公交车。','Choose a vehicle for a ride on the road.','bus'),('想乘车走铁轨，选火车。','Choose a vehicle that travels on rails.','engine'),('想乘船过河，选船。','Choose a vessel for crossing water.','boat')]
 routines_lang=[('先洗手，再擦干。','Wash hands, then dry.',['wash','dry']),('先穿袜子，再穿鞋。','Put on socks, then shoes.',['sock','shoe']),('先种下种子，再看到芽。','Plant a seed, then see a sprout.',['seed','sprout']),('先看到芽，再看到长大的植物。','See a sprout, then a larger plant.',['sprout','plant']),('故事里先下雨，后来出太阳。','In this story rain comes, then sunshine.',['rain','sun']),('故事里先跑步，再躺下休息。','In this story run, then rest in bed.',['run','bed']),('故事里先拿钥匙，再打开门。','In this story take a key, then open a door.',['key','door']),('故事里先吃饭，再睡觉。','In this story eat, then sleep.',['eat','sleep']),('故事里先看书，再上床。','In this story read a book, then go to bed.',['book','bed']),('故事里先下雨，再撑伞。','In this story rain begins, then an umbrella opens.',['rain','umbrella']),('故事里先播放音乐，再安静下来。','In this story music plays, then it becomes quiet.',['music','quiet']),('故事里先洗手，再吃饭。','In this story wash hands, then eat.',['wash','eat'])]
 # Each bilingual paragraph has distinct events and a stated cause, preserving meaning across tasks.
 passages=[
 ('下雨了。小兔把书放进包里，走进屋子。书没有淋湿。','Rain began. Rabbit put a book in a bag and went inside. The book stayed dry.',['下雨','把书放进包里','进屋'],['Rain begins','Put the book in a bag','Go inside'],'下雨了','Rain began','把书放进包里','Put the book in a bag','小兔在屋里拿出干燥的书','Rabbit takes out the dry book indoors'),
 ('小猫口渴了。小狗端来一杯水。小猫喝水后说谢谢。','Cat was thirsty. Dog brought water. Cat drank it and said thank you.',['小猫口渴','小狗拿水','小猫喝水'],['Cat is thirsty','Dog brings water','Cat drinks'],'小猫口渴了','Cat was thirsty','小狗端来了水','Dog brought water','小猫把空杯放回桌上','Cat puts the empty cup on the table'),
 ('小熊的手脏了。小熊先洗手，再用毛巾擦干。手变干净了。','Bear had dirty hands. Bear washed them and dried them with a towel. The hands were clean.',['手脏了','洗手','擦干'],['Hands are dirty','Wash','Dry'],'手脏了','The hands were dirty','小熊洗了手','Bear washed the hands','小熊收好毛巾','Bear puts the towel away'),
 ('小鸟的食盆空了。小猫添上食物。小鸟走到食盆边吃东西。','Bird’s food bowl was empty. Cat added food. Bird came over and ate.',['食盆空了','添食物','小鸟吃东西'],['Bowl is empty','Add food','Bird eats'],'食盆空了','The bowl was empty','小猫添了食物','Cat added food','小鸟吃完后离开食盆','Bird leaves after eating'),
 ('球滚到桌下。小狗弯腰把球拿出来，再放进盒子。球收好了。','A ball rolled under the table. Dog retrieved it and put it in a box. The ball was put away.',['球滚到桌下','拿出球','放进盒子'],['Ball rolls under table','Retrieve ball','Put ball in box'],'球滚到桌下','The ball rolled under the table','球放进了盒子','The ball was put in the box','小狗合上装球的盒子','Dog closes the box holding the ball'),
 ('小兔的鞋湿了。小兔脱下鞋，放在通风处，换上干袜子。','Rabbit’s shoes were wet. Rabbit took them off, left them in an airy place and put on dry socks.',['鞋湿了','脱下鞋','换干袜子'],['Shoes are wet','Take off shoes','Put on dry socks'],'鞋湿了','The shoes were wet','换上了干袜子','Rabbit put on dry socks','小兔等鞋晾干','Rabbit waits for the shoes to dry'),
 ('小熊找不到钥匙。小熊看了桌子，又检查口袋，在口袋里找到了钥匙。','Bear could not find a key. Bear checked the table, then a pocket, and found the key in the pocket.',['找不到钥匙','检查桌子','检查口袋'],['Key is missing','Check table','Check pocket'],'找不到钥匙','The key was missing','钥匙在口袋里','The key was in the pocket','小熊拿出找到的钥匙','Bear takes out the found key'),
 ('音乐很响。小猫请求调低音量。小狗把音量调小，小猫继续看书。','Music was loud. Cat asked for a lower volume. Dog lowered it and Cat continued reading.',['音乐很响','请求调小','调低音量'],['Music is loud','Request lower volume','Lower volume'],'音乐很响','The music was loud','音量调低了','The volume was lowered','小猫在较安静的房间看书','Cat reads in the quieter room'),
 ('小狗画错了一条线。小狗擦掉那条线，重新画好，再把画交给老师。','Dog drew a wrong line. Dog erased it, redrew it and gave the picture to the teacher.',['画错线','擦掉线','重新画'],['Draw wrong line','Erase line','Redraw line'],'画错了一条线','A wrong line was drawn','重新画好了','Dog redrew the line','老师看到修改好的画','The teacher sees the revised picture'),
 ('小兔想坐公交车。小兔走到站牌，排队，然后上车。','Rabbit wanted a bus ride. Rabbit walked to the stop, queued and boarded.',['走到站牌','排队','上车'],['Go to stop','Queue','Board bus'],'想坐公交车','Rabbit wanted a bus ride','小兔走到站牌并排队','Rabbit went to the stop and queued','公交车载着小兔出发','The bus departs with Rabbit aboard'),
 ('植物的土干了。小熊浇了水。水慢慢渗进土里，土变湿了。','A plant’s soil was dry. Bear watered it. Water soaked into the soil and it became damp.',['土干了','浇水','土变湿'],['Soil is dry','Water soil','Soil becomes damp'],'土干了','The soil was dry','小熊浇了水','Bear watered the soil','小熊收好浇水的杯子','Bear puts away the watering cup'),
 ('门口有一摊水。小猫停下，告诉老师。老师擦干了水，小猫再走过去。','There was a puddle by the door. Cat stopped and told the teacher. The teacher dried it before Cat passed.',['发现水','告诉老师','擦干水'],['Notice water','Tell teacher','Dry water'],'门口有水','There was water by the door','老师擦干了水','The teacher dried the water','小猫经过干燥的门口','Cat passes the dry doorway')]
 for lang in ['chinese','english']:
  zh=lang=='chinese'
  def L(c,e):return c if zh else e
  replace(lang,1,0,[Q('',[A(a),A(nouns[(i+1)%len(nouns)][2]),A(nouns[(i+2)%len(nouns)][2])],narration=L('大人读：'+ch,'Grown-up says: '+en),cue=L('听大人读词，再选图片。','Listen to the grown-up, then choose a picture.'),explain=L('这是'+ch+'。','This is a '+en+'.')) for i,(ch,en,a) in enumerate(nouns)])
  replace(lang,1,1,[Q('',[A(a)]+[A(b) for b in ['wash','run','eat'] if b!=a][:2],narration=L('大人读：'+c,'Grown-up says: '+e),cue=L('听一听，选动作。','Listen, then choose the action.'),explain=L('选图与动作相符。','The selected picture matches the stated action.')) for c,e,a in action_contexts])
  replace(lang,1,2,[Q('',[A(a),A('book' if a!='book' else 'cup'),A('key' if a!='key' else 'shoe')],narration=L(c,e),cue=L('听故事，选物品。','Listen to the scene and choose an object.'),explain=L('这个物品符合用途。','This object fits the stated use.')) for c,e,a in contexts])
  replace(lang,2,0,[Q(ch,[A(a),A(nouns[(i+1)%len(nouns)][2]),A(nouns[(i+2)%len(nouns)][2])],explain='字和图的意思相符。') for i,(ch,en,a) in enumerate(nouns)] if zh else [Q(chr(65+i),[chr(97+i),chr(97+(i+1)%26),chr(97+(i+7)%26)],explain='The capital and lowercase forms name the same letter.') for i in range(26)])
  replace(lang,2,1,[Q(L(ch,en),[A(a),A(nouns[(i+1)%len(nouns)][2]),A(nouns[(i+3)%len(nouns)][2])],explain=L('标签与物品相符。','The label names this object.')) for i,(ch,en,a) in enumerate(nouns)])
  replace(lang,2,2,[O(L(c,e),[A(a) for a in items],L('顺序与提示相符。','The sequence follows the prompt.')) for c,e,items in routines_lang])
  printed=['火车','书包','雨伞','小猫','小狗','水杯','书本','小鸟','公交车','门口','白云','花朵'] if zh else ['cat','dog','cup','book','key','sock','shoe','fish','bird','ball','door','bed','bus','boat']
  replace(lang,3,0,[O(L('照着示例组合：','Copy the printed word: ')+word,list(word),L('字词顺序与示例相符。','The letters match the printed model; this is not sound blending.')) for word in printed])
  phrase=[];meaning=[]
  for ch,en,a in nouns[:6]:
   for z in ['small','large']:
    other='large' if z=='small' else 'small'
    phrase.append(Q(L(('小' if z=='small' else '大')+ch,('a small ' if z=='small' else 'a big ')+en),[dict(A(a),scale=z),dict(A(a),scale=other),A('shoe')],explain=L('选图的大小与词语相符。','The pictured size matches the phrase.')))
   for pos,cpos,epos in [('on','桌子上面','on the table'),('under','桌子下面','under the table'),('in','盒子里面','in the box'),('out','盒子外面','outside the box')]:
    opts=[A(a+'-'+p) for p in [pos]+[p for p in ['on','under','in','out'] if p!=pos][:2]]
    meaning.append(Q(L(ch+'在'+cpos+'。','The '+en+' is '+epos+'.'),opts,explain=L('物品的位置符合句子。','The location matches the sentence.')))
  replace(lang,3,1,phrase);replace(lang,4,0,meaning)
  chars=[('小猫','Cat','cat'),('小狗','Dog','dog'),('小兔','Rabbit','rabbit0'),('小熊','Bear','bear0')]
  replace(lang,3,2,[Q(L(ca+'把书递给'+cb+'。谁递书？',ea+' gives a book to '+eb+'. Who gives the book?'),[A(aa),A(ab),A('bird')],explain=L(ca+'递书。',ea+' is the giver.')) for (ca,ea,aa),(cb,eb,ab) in permutations(chars,2)])
  verbs=[('拿着','holds','书','a book'),('看着','looks at','球','a ball'),('推着','pushes','玩具车','a toy car')]
  replace(lang,4,1,[O(L('排列句子：谁 / 动作 / 物品','Build: who / action / object'),[L(ca,ea),L(vc,ve),L(ob,oe)],L(ca+vc+ob+'。',ea+' '+ve+' '+oe+'.')) for ca,ea,aa in chars for vc,ve,ob,oe in verbs])
  replace(lang,4,2,[Q(L(c+'应该选____。',e+' Which object fits?'),[L(next(ch for ch,en,ar in nouns if ar==a),next(en for ch,en,ar in nouns if ar==a)),L('石头','a stone'),L('空纸袋','an empty paper bag')],explain=L('这个词符合情境。','This word fits the stated purpose.')) for c,e,a in contexts])
  for pi,row in enumerate(passages):
   c,e,cs,es,cc,ec,proofc,proofe,endc,ende=row;p=L(c,e)
   add(lang,5,0,[O(p+' '+L('按故事顺序排列。','Order the events.'),L(cs,es),L('顺序与故事相符。','The order matches the story.'))])
   add(lang,5,1,[Q(p+' '+L('哪条原因或背景是故事明确写出的？','Which cause or background is explicitly stated?'),[L(cc,ec),L(passages[(pi+1)%12][4],passages[(pi+1)%12][5]),L(passages[(pi+3)%12][4],passages[(pi+3)%12][5])],explain=L('这条信息明确写在故事里。','This information is explicitly in the passage.'))])
   claims=[
    ('书可能因为被收进包里而保持干燥','The bag may have helped protect the book','书本从不会被水弄湿','Books can never get wet','没有下雨','No rain fell'),
    ('小猫喝水后可能不那么口渴了','Cat may be less thirsty after drinking','小猫从来不会口渴','Cat can never be thirsty','小狗把水藏了起来','Dog hid the water'),
    ('洗手可能帮助去掉手上的脏东西','Washing may have helped remove dirt','毛巾让所有脏东西凭空消失','A towel always removes every kind of dirt by itself','小熊没洗手','Bear never washed'),
    ('添食物可能让小鸟有东西吃','Adding food may have let Bird eat','空食盆一直装满食物','The empty bowl was already full','小鸟没有走到食盆边','Bird never came to the bowl'),
    ('把球放进盒子可能让它更容易找到','Putting the ball in a box may make it easier to find','球仍然在桌下','The ball is still under the table','小狗没有找到球','Dog never found the ball'),
    ('换干袜子可能让脚感觉更干爽','Dry socks may help the feet feel drier','湿鞋已经被证实完全干了','The wet shoes are proven completely dry','小兔没有换袜子','Rabbit never changed socks'),
    ('继续检查口袋可能帮助小熊找到了钥匙','Checking the pocket may have helped Bear find the key','钥匙肯定在桌上','The key is definitely on the table','小熊把钥匙丢进河里','Bear threw the key into a river'),
    ('音量调小可能让小猫更容易继续阅读','Lower volume may have made continuing to read easier','音乐变得更响了','The music became louder','小猫不想看书','Cat did not want to read'),
    ('擦掉再重画可能帮助修改那条线','Erasing and redrawing may have helped revise the line','原来的线从没改过','The original line was never changed','老师代替小狗画了整张画','The teacher drew the whole picture instead'),
    ('去站牌排队可能帮助小兔顺利上车','Going to the stop and queuing may have helped Rabbit board','小兔一直待在床上','Rabbit stayed in bed throughout','公交车从没到站','The bus never arrived'),
    ('浇水可能使干土变湿','Watering may have made the dry soil damp','土原来一直是湿的','The soil was already damp throughout','植物把土变成了石头','The plant turned soil into stone'),
    ('等老师擦干水可能减少经过时滑倒的风险','Waiting for the teacher to dry the water may reduce slipping risk','地面一直没有水','There was never water on the floor','小猫跑过了湿水洼','Cat ran through the wet puddle')]
   claimc,claime,wc,we,vc,ve=claims[pi]
   add(lang,6,0,[S(Q(p+' '+L('哪个推断最有故事线索支持？','Which inference has the best support in this story?'),[L(claimc,claime),L(wc,we),L(vc,ve)]),Q(L('哪条故事信息支持刚才的推断？','Which stated detail supports that inference?'),[L(proofc,proofe),L(passages[(pi+1)%12][6],passages[(pi+1)%12][7]),L(passages[(pi+3)%12][6],passages[(pi+3)%12][7])],explain=L('线索支持一个可能的解释，不证明所有情况。','The detail supports a possible explanation, not a universal claim.')))])
   add(lang,6,1,[Q(p+' '+L('哪个结尾保持故事信息一致？','Which ending keeps the stated details consistent?'),[L(endc,ende),L(passages[(pi+1)%12][8],passages[(pi+1)%12][9]),L(passages[(pi+3)%12][8],passages[(pi+3)%12][9])],explain=L('这个结尾延续原有事件，没有否定前文。','This ending continues the events without contradicting them.'))])
  references=[];edits=[]
  for (ca,ea,aa),(cb,eb,ab) in permutations(chars,2):
   references.append(Q(L(ca+'拿着书，对'+cb+'说：“这是我的书。”书是谁的？',ea+' holds a book and says to '+eb+', “This is my book.” Whose book is it?'),[L(ca,ea),L(cb,eb),L('小鸟','Bird')],explain=L('“我的”指说话的人。','My refers to the speaker.')))
   edits.append(Q(L(ca+'和'+cb+'站在门旁。“他开门。”怎样明确写出是'+ca+'开门？',ea+' and '+eb+' stand by a door. “He opens it.” Which revision explicitly says '+ea+' is the opener?'),[L(ca+'打开门。',ea+' opens the door.'),L('他打开门。','He opens it.'),L(cb+'打开门。',eb+' opens the door.')],explain=L('直接写出人物名字，意思更明确。','Naming the intended actor resolves the ambiguity.')))
  replace(lang,5,2,references);replace(lang,6,2,edits)
 # Science: bounded original observation records, not claims that an app ran an experiment.
 parts=[('Which picture shows a leaf?','leaf'),('Which picture shows a seed before sprouting?','seed'),('Which picture shows a young sprout?','sprout'),('Which picture shows a larger plant with several leaves?','plant'),('Which part is a flower?','flower'),('Which part is a root?','root'),('Which part is a stem?','stem'),('Which picture shows a fruit?','fruit'),('A seed was put into soil. Choose the seed picture.','seed'),('A shoot appeared above the soil. Choose the sprout.','sprout'),('A flower opened on the plant. Choose the flower.','flower'),('Roots were seen below the soil. Choose the roots.','root')]
 replace('science',1,0,[Q(p,[A(a),A('leaf' if a!='leaf' else 'seed'),A('flower' if a!='flower' else 'stem')],explain='This picture names the stated part or growth stage.') for p,a in parts])
 replace('science',1,1,[Q(p+' Which object fits?',[A(correct),A('book' if correct!='book' else 'shoe'),A('key' if correct!='key' else 'ball')],explain='This object fits the specified use.') for p,clue,correct in uses])
 visible=[('Which pictured weather shows falling water drops?','rain','sun','leaf'),('Which picture shows an outlined round ball?','ball','book','key'),('Which animal picture has fins?','fish','cat','bird'),('Which picture shows the animal with the pictured pointed ears?','cat','dog','fish'),('Which vehicle picture shows wheels for the road?','bus','boat','fish'),('Which picture shows a leaf with an edge and veins?','leaf','water','sun'),('Which picture shows a sprout above soil?','sprout','seed','cup'),('Which picture shows rays around a round center?','sun','rain','seed'),('Which picture shows a vessel on water?','boat','door','shoe'),('Which picture shows an umbrella canopy?','umbrella','book','cup'),('Which picture shows a solid door frame and handle?','door','leaf','fish'),('Which picture shows a cup with a handle?','cup','ball','shoe')]
 replace('science',1,2,[Q(p,[A(a),A(b),A(c)],explain='The stated visible feature is shown in this picture.') for p,a,b,c in visible])
 replace('science',2,0,rules[:])
 weather=[('Rain is falling. Which object helps keep it off?','umbrella'),('Wet hands need drying. Which item is a towel?','dry'),('After active play, a child wants drinking water. Which container fits?','cup'),('Shoes are needed for walking outside. Choose footwear.','shoe'),('Feet need a layer inside shoes. Choose socks.','sock'),('A plant has dry soil; an adult plans to water it. Choose water.','water'),('A child is tired and wants to rest. Choose a bed.','bed'),('We want to watch a leaf without pulling the plant. Choose its leaf picture.','leaf'),('Rain began during a walk. Choose an umbrella.','umbrella'),('After washing, a cloth is wet. Choose a drying towel.','dry'),('A cup needs filling with drinking water. Choose the water.','water'),('We are planting today. Choose a seed to put in soil.','seed')]
 replace('science',2,1,[Q(p,[A(a),A('book' if a!='book' else 'shoe'),A('key' if a!='key' else 'ball')],explain='This choice fits the stated situation; adults check safe real-world use.') for p,a in weather])
 # Distinct stated growth/observation orders, rather than renaming the same plant.
 growth=[(['seed','sprout','plant'],'The record shows a seed, then a sprout, then a larger plant.'),(['sprout','plant','flower'],'The record shows a sprout, then a larger plant, then a flower.'),(['flower','fruit','seed'],'In this record a flower is followed by a fruit, then exposed seeds.'),(['seed','root','sprout'],'This record first shows a seed, then a root, then a shoot above soil.'),(['plant','flower','fruit'],'This record shows a leafy plant, then a flower, then a fruit.'),(['root','stem','leaf'],'This diagram was uncovered in order: root, stem, then leaf.'),(['leaf','flower','fruit'],'In this observation album the leaf photo comes before flower, then fruit.'),(['seed','sprout'],'Two records: seed before sprout.'),(['sprout','leaf'],'Two records: sprout before a new leaf opens.'),(['flower','fruit'],'Two records: flower before fruit.'),(['fruit','seed'],'Two records: fruit before its seeds are removed.'),(['root','plant'],'Two records: a root appears before the leafy plant photo.')]
 replace('science',2,2,[O(p+' Arrange the stated record.',[A(a) for a in items],'The order matches this supplied record, not every plant life cycle.') for items,p in growth])
 trials=[('left side high','lower right','higher left','the lower right'),('right side high','lower left','higher right','the lower left'),('paper towel and plastic lid','towel','lid','the towel absorbed the drop; the lid did not'),('cotton cloth and glass tile','cloth','tile','the cloth absorbed the drop; the tile did not'),('sponge and metal tray','sponge','tray','the sponge absorbed the drop; the tray did not'),('hollow block and solid stone','hollow block','stone','the hollow block floated; the stone sank'),('rough ramp and smooth ramp','rough ramp','smooth ramp','the ball stopped sooner on the rough ramp'),('shade and sun puddles','sun puddle','shade puddle','both shrank; the sun puddle shrank more'),('warm and cool wet cloths','warm cloth','cool cloth','the warm cloth dried sooner'),('covered and open cups','open cup','covered cup','the open cup lost more visible water'),('steel clip and wood block','steel clip','wood block','the tested magnet attracted the steel clip only'),('paper sheet and folded paper','folded paper','flat sheet','the folded paper supported the toy; the flat sheet bent')]
 def predict(p,opts,obs,follow,answers,explain):return S(dict(Q(p,opts),mode='predict',observation=obs),Q('Observed record: '+obs+' '+follow,answers,explain=explain,cue='Use the supplied observation.'))
 replace('science',3,0,[predict('Setup: '+setup+'. Which result might occur?',[a,b],'In this supplied trial, '+result+'.','Which report fits this trial?',[result,'Both tested objects always behave identically','This proves a rule for every object'],'Report this trial without extending it to untested objects.') for setup,a,b,result in trials])
 measures=[('leaf count',2,4,2,2),('height marks',3,5,3,3),('open flower count',0,2,0,0),('wet area marks',8,4,8,8),('distance marks',2,6,2,2),('visible holes',1,3,1,1),('water level marks',7,5,7,7),('root length marks',1,4,1,1),('seed count visible',3,5,3,3),('fold count',0,2,0,0),('shadow length marks',4,7,4,4),('dry patches',1,3,1,1)]
 replace('science',3,1,[Q('Record of '+kind+': A first '+str(a)+', later '+str(b)+'. B first '+str(c)+', later '+str(d)+'. Which object changed?',['A changed; B stayed at the recorded value','B changed; A stayed the same','Both stayed the same'],explain='Compare each object’s first and later recorded values.') for kind,a,b,c,d in measures])
 replace('science',3,2,[Q('Supplied record: '+kind+' first '+str(a)+', later '+str(b)+'. What changed?',['The recorded value '+('increased' if b>a else 'decreased'),'The value stayed the same','The record establishes the reason for the change'],explain='The record describes a change; it alone does not identify a cause.') for kind,a,b,c,d in measures])
 obs=[('This leaf has holes','This leaf may develop more holes tomorrow'),('The ball stopped at the line','The ball may travel farther next time'),('The cloth is wet now','The cloth may dry later'),('The seed has a visible root','A leaf may appear tomorrow'),('There are two open flowers','Another flower may open soon'),('The cup water is at this mark','The level may be lower tomorrow'),('The ramp surface feels rough','A ball may stop sooner on this ramp'),('The paper has one fold','Another fold may support more weight'),('The shadow reaches this line','The shadow may be shorter later'),('The magnet attracted this clip','A different clip may also be attracted'),('The puddle covers half the chalk circle','The puddle may shrink this afternoon'),('The stone is at the bottom','Another stone may sink too')]
 replace('science',4,0,[Q('Which statement is an observation now?',[a,b,'Every object will behave the same forever'],explain='An observation reports a present or recorded detail; the other statement predicts.') for a,b in obs])
 replace('science',4,1,[Q('Two records of '+kind+': A '+str(a)+' → '+str(b)+'; B '+str(c)+' → '+str(d)+'. Which statement is supported?',['A changed; B did not change','B changed more than A','These records prove what caused the change'],explain='This compares the given records without inventing a cause.') for kind,a,b,c,d in measures])
 factors=[('ramp height','same ball and surface','stopping distance'),('ramp surface','same ball and height','stopping distance'),('paper type','same size and water drop','absorption time'),('cloth type','same size and wetness','drying time'),('water amount','same plant kind, soil and light','growth marks'),('light condition','same plant kind, soil and water','growth marks'),('paper folds','same paper and toy load','supported load'),('magnet distance','same magnet and clip','attraction result'),('cup cover','same cup and starting water','water level change'),('shade','same starting wet area and surface','wet area change'),('ball type','same ramp height and surface','travel distance'),('soil type','same plant kind, water and light','growth marks')]
 replace('science',4,2,[Q('We can vary '+factor+' while keeping '+matched+'. Which question can this compare?',['Does '+factor+' change the recorded '+measure+'?','Which setup is the best in every way?','Will every object behave this way forever?'],explain='The question names the changed factor and an observable outcome.') for factor,matched,measure in factors])
 for l,f in [(5,0),(6,1)]:
  replace('science',l,f,[Q('We want to investigate '+factor+'. Which next comparison helps isolate it?',['Keep '+matched+'; change only '+factor,'Change several other conditions too','Keep '+factor+' identical and change the target of the question'],explain='Match other stated conditions and vary the factor being investigated.') for factor,matched,measure in factors])
 replace('science',5,1,[Q('Recorded '+kind+' in three trials: A '+str(a)+', '+str(a+1)+', '+str(a)+'; B '+str(b)+', '+str(b+1)+', '+str(b)+'. Which conclusion fits?',['A had '+('smaller' if a<b else 'larger')+' recorded values in these trials','All objects always have identical values','This alone proves the cause of the difference'],explain='The conclusion stays within these supplied trials.') for kind,a,b,c,d in measures])
 replace('science',5,2,[predict('Before testing '+setup+', you predicted identical outcomes. Choose a guess.',['Same recorded outcome','Different recorded outcomes'],'The supplied repeated trials show '+result+'.','How should we respond?',['Update the prediction and compare again under matched conditions','Erase any result that differs from the guess','Claim that this proves every possible case'],'Evidence can revise a prediction; matched conditions and more tests still matter.') for setup,a,b,result in trials])
 replace('science',6,0,[Q('Two trials differed in '+factor+' AND another condition. Their '+measure+' differed. What can we conclude about '+factor+' alone?',['This comparison cannot isolate '+factor+' from the other change',factor+' alone certainly caused everything','The other condition certainly had no effect'],explain='Changing two factors leaves competing explanations.') for factor,matched,measure in factors])
 replace('science',6,2,[S(Q('Supplied trials with '+setup+' showed '+result+'. Which claim fits?',[result,'All untested objects behave exactly this way','No trial happened']),Q('What limitation matters?',['The record only covers these specified objects and conditions','We have tested every object everywhere','The first result removes the need for other evidence'],explain='A supported report is bounded by the stated observations.')) for setup,a,b,result in trials])

 # Social stories change the dilemma, needs or consequence, not merely the character.
 events=[('A book fell from Rabbit’s bag.','book'),('Bear spilled water beside the table.','water'),('A toy ball rolled under the table.','ball'),('Cat left a key by the door.','key'),('Dog put shoes by the bed.','shoe'),('Bird carried a leaf to the window.','leaf'),('Rabbit brought an umbrella for the rain.','umbrella'),('Bear set a cup on the table.','cup'),('Cat opened a book at the desk.','book'),('Dog placed socks beside shoes.','sock'),('Rabbit parked a toy bus by the door.','bus'),('Bear put a seed in soil.','seed')]
 replace('stories',1,0,[Q(p+' Which item was mentioned?',[A(a),A('ball' if a!='ball' else 'key'),A('shoe' if a!='shoe' else 'book')],explain='This item is explicitly named in the story.') for p,a in events])
 feelings=[('A favorite toy is missing.','rabbit0','Sad','Worried'),('The playground is new.','bear0','Excited','Unsure'),('A tower fell.','blocks','Frustrated','Disappointed'),('A friend came back after a trip.','cat','Happy','Shy'),('A loud noise happened.','music','Startled','Uncomfortable'),('A game ended before a turn.','ball','Disappointed','Frustrated'),('A drawing was finished.','book','Proud','Relieved'),('A child is waiting for family.','wait','Eager','Worried'),('A new food is offered.','cup','Curious','Unsure'),('A friend asks to join.','dog','Happy','Unsure'),('A plan changed suddenly.','door','Surprised','Disappointed'),('A room feels crowded.','house','Uncomfortable','Worried')]
 replace('stories',1,1,[B(p+' What might the character feel?',a,[(x,x+' is one possibility; we can ask.'),(y,y+' is another possibility; people differ.'),('Not sure','We need the person’s own words or signals, not a mind-reading guess.')]) for p,a,x,y in feelings])
 comfort=[('A tower fell and Bear looks upset.','blocks','Ask whether rebuilding help is wanted','Offer quiet company'),('Rabbit is tired after play.','bed','Offer a quiet place','Ask what rest would help'),('Cat misses a friend.','cat','Listen if Cat wants to talk','Ask if drawing a message would help'),('Dog is upset after losing a game.','ball','Offer time to pause','Ask whether company is wanted'),('A noise startled Bird.','music','Offer a quieter spot','Ask what would feel comfortable'),('Rabbit’s drawing tore.','book','Ask whether repair help is wanted','Offer to sit nearby'),('Bear is unsure in a new room.','door','Offer to look around together','Ask whether a familiar adult would help'),('Cat is waiting longer than expected.','wait','Explain what information we have','Offer company while waiting'),('Dog feels overwhelmed by a busy game.','dog','Offer a pause','Ask if a quieter activity would help'),('Rabbit is disappointed about rain.','rain','Listen to the disappointment','Ask about an indoor activity'),('Bear made a mistake in a puzzle.','blocks','Ask if help is wanted','Allow time to try again'),('Bird does not want to talk yet.','quiet','Offer space','Stay available without demanding a reply')]
 replace('stories',1,2,[B(p,a,[(x,'This offers support while leaving the person a choice.'),(y,'This is another possible response; check what the person needs.')]) for p,a,x,y in comfort])
 replace('stories',2,0,[O(p+' Then a friend noticed the item. Finally an adult helped put it away. Arrange these stated events.',[p,'A friend notices the item','An adult helps put it away'],'The order follows the stated story.') for p,a in events])
 help=[('A book is too high to reach safely.','book','Ask a trusted adult to retrieve it','Choose a reachable book while waiting'),('A child cannot find the classroom door.','door','Ask the familiar teacher','Stay with a trusted adult while asking'),('Shoelaces are tangled.','shoe','Ask a trusted adult to help','Sit safely while waiting for help'),('A cup spills on the floor.','cup','Tell an adult about the slippery spot','Keep away while asking for cleanup help'),('A toy is under a heavy cupboard.','ball','Ask an adult instead of moving the cupboard','Choose another toy while waiting'),('The game rules are confusing.','blocks','Ask someone to explain one step','Ask a trusted adult for help'),('A bag cannot be opened.','book','Ask for help opening it','Set it down safely while asking'),('A child feels lost on a school outing.','bus','Stay with the group’s trusted adult','Tell the familiar teacher right away'),('A plant pot is too heavy.','plant','Ask an adult to move it','Leave it safely in place'),('A door is difficult to open.','door','Ask a trusted adult','Wait safely without forcing it'),('A child does not know where drinking water is.','water','Ask the familiar teacher','Ask a trusted adult to show the water place'),('A broken toy has a sharp edge.','engine','Leave it and tell an adult','Ask for a safe replacement')]
 replace('stories',2,1,[B(p,a,[(x,'This seeks help without taking an unnecessary risk.'),(y,'This is another possible safe response.')]) for p,a,x,y in help])
 needs=[('Rabbit says “I am thirsty.”','water','Offer drinking water','Ask where to find water'),('Bear says “I need quiet.”','music','Offer a quieter spot','Ask about lowering the volume'),('Cat says “I am tired.”','bed','Offer a rest','Ask what kind of rest helps'),('Dog says “I want to watch first.”','ball','Allow watching','Offer game information without forcing participation'),('Rabbit says “I need more room.”','table','Make space if possible','Ask which space would help'),('Bear says “I cannot hear the rule.”','quiet','Repeat it clearly','Find a quieter place to explain'),('Cat says “My hands are wet.”','wash','Offer a towel','Show where a towel can be found'),('Dog says “My feet are cold.”','sock','Offer suitable socks with adult help','Ask an adult about warmer clothing'),('Rabbit says “I want to finish this drawing.”','book','Offer time to finish','Ask about a later turn'),('Bear says “I need help with this puzzle.”','blocks','Ask which step is confusing','Offer to work on a step together'),('Cat says “I want to sit alone for a bit.”','cat','Respect space','Stay available for later support'),('Dog says “I am unsure about the new room.”','door','Offer a look around together','Ask whether a familiar adult would help')]
 replace('stories',2,2,[B(p,a,[(x,'This addresses the stated need; check whether it helps.'),(y,'The character can choose whether this support is wanted.')]) for p,a,x,y in needs])
 conflicts=[('finish a tower','have a turn with blocks','blocks'),('hear music','read quietly','music'),('finish a drawing','use the table for a puzzle','table'),('keep using a toy train','try the train','engine'),('run a fast game','watch the game first','ball'),('sit with a friend','sit alone briefly','quiet'),('open a window','avoid a cold breeze','house'),('tell a story now','finish listening to another person','book'),('use a cup for a pretend game','have a cup for a drink','cup'),('keep a game’s familiar rules','learn the rules before joining','blocks'),('save an unfinished paper model','clear enough space for lunch','table'),('walk slowly to look at leaves','reach the meeting place on time','leaf')]
 replace('stories',3,0,[Q('Rabbit wants to '+a+'. Bear wants to '+b+'. Which statement recognizes both?',['Rabbit wants to '+a+'; Bear wants to '+b,'Only Rabbit’s wish matters','Bear must have the same wish as Rabbit'],explain='Both stated viewpoints can be recognized before planning.') for a,b,art in conflicts])
 boundaries=[('Rabbit is still using a toy.','engine','Say “I am still using it; please ask for a turn.”','Ask an adult to help arrange turns'),('Bear does not want a hug.','bear0','Say “No hug, thank you.”','Offer a wave if wanted'),('Cat does not want a photo now.','cat','Say “Please do not take my photo.”','Ask a trusted adult for support'),('Dog needs room at the table.','table','Ask for enough space','Seek adult help if the request is ignored'),('Rabbit wants a pause in rough play.','ball','Say “Stop; I need a pause.”','Move safely toward a trusted adult'),('Bear wants a private drawing kept closed.','book','Ask others not to open it','Ask an adult to help protect that boundary'),('Cat does not want to join yet.','cat','Say “I will watch first.”','Ask for information without joining'),('Dog does not want a nickname.','dog','Ask to use Dog’s preferred name','Ask a trusted adult for support'),('Rabbit does not want a hand held now.','rabbit0','Say “No hand-holding right now.”','Choose another safe way to stay together with adult guidance'),('Bear needs a quiet break.','quiet','Ask for a quiet pause','Ask an adult where a quiet space is'),('Cat is not ready to talk.','cat','Say “I will talk later.”','Ask for company without conversation'),('Dog does not want a friend to move the puzzle.','blocks','Ask to leave the puzzle in place','Ask for help finding another workspace')]
 replace('stories',3,1,[B(p,a,[(x,'The character states a boundary; others should respect it.'),(y,'Support and alternatives remain optional; safety guidance can still matter.')]) for p,a,x,y in boundaries])
 mistakes=[('A tower was knocked down accidentally.','blocks'),('Water spilled near a friend’s book.','cup'),('A drawing was moved without asking.','book'),('A toy was put in the wrong box.','ball'),('A friend’s name was mispronounced.','dog'),('A turn was skipped by mistake.','wait'),('A door was closed before a friend passed.','door'),('A puzzle piece was taken by mistake.','blocks'),('A leaf collection was mixed up.','leaf'),('A borrowed sock puppet was left out.','sock'),('Music was started during a quiet activity.','music'),('A toy train track was shifted without asking.','engine')]
 replace('stories',3,2,[B(p+' How might we begin repair?',a,[('Acknowledge what happened and ask what would help','Acknowledgment and asking can guide repair.'),('Offer help while respecting a request for space','Help can be offered; the person can choose timing and support.')]) for p,a in mistakes])
 risky=[('Both children want the toy train.','engine','Ask for a turn','A request opens a possible turn plan.','Grab the train','Grabbing may upset someone or cause harm.'),('A tower fell and Bear is angry.','blocks','Take a pause','A pause may allow a safer next choice.','Throw a block','A thrown block could hurt someone.'),('Music is disturbing a reader.','music','Ask about a quieter arrangement','A request can open a shared plan.','Turn it louder','Louder music may make reading harder.'),('A child wants to use a friend’s drawing.','book','Ask permission','The friend can decide whether to share.','Take it without asking','Taking it may cross a boundary.'),('Two children reach a narrow door.','door','Make space to pass safely','Space can help avoid bumping.','Push past','Pushing may cause a fall.'),('A spill blocks the path.','water','Keep away and tell an adult','An adult can help with the slippery spot.','Run through it','Running there could cause slipping.'),('A game rule is confusing.','ball','Ask for clarification','An explanation can support participation.','Shout over everyone','Shouting may make the explanation harder to hear.'),('A child wants a seat already in use.','bed','Ask about another seat or a later turn','A request can preserve the current user’s space.','Pull the seat away','Pulling it could cause a fall.'),('A child wants attention while a friend speaks.','dog','Wait for a pause','A pause may allow both to be heard.','Keep interrupting','Interruptions may stop the friend being heard.'),('A puzzle piece seems missing.','blocks','Ask to look together','Cooperation may help locate it.','Blame a friend without evidence','Blame without evidence can hurt trust.'),('A friend does not want a hug.','bear0','Respect the no','Respecting the boundary preserves choice.','Hug anyway','Unwanted touch crosses the stated boundary.'),('A toy has a sharp broken edge.','engine','Leave it and ask an adult','An adult can help choose a safe response.','Keep swinging it','The sharp edge could injure someone.')]
 replace('stories',4,0,[B2(p,a,[(x,rx),(y,ry)],[('Pause and check what everyone needs','Checking needs can support a safer plan.'),('Ask a trusted adult for help','Adult help is a valid next step when safety or a conflict is difficult.')]) for p,a,x,rx,y,ry in risky])
 replace('stories',4,1,[Q(p+' Which statement separates a feeling from a required action?',['This feeling can make sense; we can choose a safe response','This feeling requires hurting someone','Nobody is allowed to feel this way'],explain='Feelings can be accepted while actions are chosen safely.') for p,a,x,y in feelings])
 replace('stories',4,2,[B(p,a,[(x,'This offers a possible plan while preserving the person’s choice.'),(y,'This is another possible plan; ask whether it helps.')]) for p,a,x,y in comfort])
 replace('stories',5,0,[B2('Rabbit wants to '+a+'. Bear wants to '+b+'. Explore a plan.',art,[('Discuss timing, space or an alternative together','Different needs may require timing, space or another option.'),('Ask an adult to help hear both needs','Support can help both needs be heard.')],[('Check whether the plan works for both','Agreement can be checked and revised.'),('Revise the plan if one need is unmet','A first plan is not final if it fails someone’s need.')]) for a,b,art in conflicts])
 replace('stories',5,1,[Q(p+' It was meant as help, but a friend was upset. Which statement recognizes intent and impact?',['Helpful intent and an upsetting effect can both be true','Helpful intent proves nobody was upset','An upsetting effect proves the action was intended to hurt'],explain='Intent does not erase impact, and impact alone does not prove harmful intent.') for p,a in mistakes])
 safe_plans=[
 ('A slippery spill blocks the doorway.',['Stay away from the wet patch','Tell a trusted adult about the spill','Pass only after the adult makes the way safe']),
 ('A toy train has a sharp broken edge.',['Stop handling the broken toy','Tell a trusted adult about the edge','Choose a safe replacement with help']),
 ('A game becomes too rough.',['Pause the rough play','Move toward a trusted adult','Describe what happened and ask for support']),
 ('A book is on a shelf too high to reach.',['Leave the high shelf alone','Ask a trusted adult to retrieve the book','Wait in a safe place']),
 ('A child is unsure of the route on a school outing.',['Stay beside the familiar group adult','Say the route is unclear','Follow the adult’s safe guidance']),
 ('A plant pot is too heavy to lift.',['Set down the attempt to lift it','Ask a trusted adult to move the pot','Make room while the adult helps']),
 ('A bag strap is caught on a hook.',['Stop pulling against the hook','Ask an adult to free the strap','Move away once it is released']),
 ('A game rule is unclear.',['Pause the game','Ask for an explanation of the rule','Decide whether to continue after understanding it']),
 ('A toy lies under a heavy cupboard.',['Leave the cupboard in place','Ask an adult about retrieving the toy','Use another safe toy while waiting']),
 ('A child wants to stop unwanted touch.',['Say stop if able','Move toward a trusted adult','Ask the adult for support']),
 ('A glass cup cracks.',['Leave the broken cup alone','Tell an adult about the pieces','Use a safe cup the adult provides']),
 ('A busy doorway is crowded.',['Pause before the crowded doorway','Ask a familiar adult for help finding space','Pass when there is a safe clear way'])]
 replace('stories',5,2,[O(p+' In this story, the plan is: '+ '; then '.join(items)+'. Arrange that stated plan.',items,'This follows the supplied plan; real children can seek adult help sooner whenever needed.') for p,items in safe_plans])
 unclear=[('A greeting went unanswered.','bear0'),('A friend left a game without explaining.','ball'),('A drawing was left unfinished.','book'),('A toy was placed in a different box.','engine'),('A child stayed at the edge of the group.','rabbit0'),('A friend looked away during a story.','cat'),('A child asked to change seats.','bed'),('A note had no name on it.','book'),('A friend arrived later than expected.','wait'),('A child declined a offered snack.','cup'),('A friend spoke very quietly.','quiet'),('A game invitation received no reply yet.','dog')]
 replace('stories',6,0,[B(p+' We do not know the reason.',a,[('Ask a gentle question','A question can gather information without deciding the intention.'),('Allow time and consider several possibilities','There may be more than one explanation.'),('Do not decide the reason yet','The available event alone does not establish intent.')]) for p,a in unclear])
 plan_cases=[
 ('Rabbit wants to finish a tower; Bear wants a turn. Both agree a short later turn is okay.','Let Rabbit finish the agreed short step, then give Bear a turn','They agreed the wait works for both'),
 ('Rabbit wants music now; Bear needs quiet now. Another room is available.','Use separate rooms for now','Separate space can address both immediate needs'),
 ('Rabbit draws; Bear wants to do a puzzle. The table is large enough for two spaces.','Agree on separate spaces on the table','There is enough room for the two activities'),
 ('Two children want one toy train. Both agree on alternating short turns.','Try the agreed alternating turns','The turn plan has agreement from both'),
 ('Rabbit wants to play; Bear wants to watch before deciding.','Allow Bear to watch while Rabbit plays','Watching preserves Bear’s choice without stopping Rabbit'),
 ('Rabbit wants company; Bear needs a short quiet pause and agrees to talk later.','Give Bear the agreed pause and reconnect later','The agreed timing can preserve space and later company'),
 ('Rabbit wants fresh air; Bear feels cold. An adult offers another ventilated space for Rabbit.','Ask the adult to help use the offered separate space','The available alternative may address both conditions'),
 ('Rabbit wants to tell a story; Bear is already speaking. Both agree to speak in turn.','Hear Bear finish, then invite Rabbit’s story','The agreed order gives both a speaking turn'),
 ('Rabbit wants a cup for pretend play; Bear needs a drink. An adult offers a spare clean cup.','Use the spare suitable cup with adult help','Two suitable cups can meet the separate uses'),
 ('Rabbit knows the game; Bear wants the rules explained before joining.','Explain the rules, then let Bear decide about joining','Information and a choice address the stated needs'),
 ('Rabbit has an unfinished model; lunch needs table space. A safe shelf is available.','Ask permission to save the model on the safe shelf','The available shelf preserves the model and frees table space'),
 ('Rabbit wants to look at leaves; Bear wants to reach a meeting on time. Both agree to look after the meeting.','Go to the meeting, then return to look at leaves','The agreed order addresses both timing and interest')]
 replace('stories',6,1,[S(Q(p+' Which plan uses the stated available option or agreement?',[plan,'Ignore Bear’s stated need','Assume both people always want identical things']),Q('Which detail supports that plan?',[reason,'One person’s wishes always count more','This is the right plan in every possible situation'],explain='Use the stated resource, agreement or need; a different situation may need another plan.')) for p,plan,reason in plan_cases])
 revision=[('A child looks upset after a game.','sad','The rules were confusing.','Explain one rule at a time','Ask a trusted adult to clarify'),('A child watches from outside the game.','rabbit0','Watching first feels better.','Respect watching first','Stay available for questions'),('A friend turns music off.','music','The sound was uncomfortable.','Discuss a quieter arrangement','Ask about another space'),('A drawing is left unfinished.','book','A pause is wanted.','Leave the drawing safely in place','Ask about returning later'),('A child moves away from a hug.','bear0','No hug is wanted.','Respect the no','Offer a wave only if wanted'),('A friend changes seats.','bed','More space is needed.','Make room if possible','Ask what space would help'),('A toy is moved aside.','engine','The toy has a loose sharp part.','Leave it and tell an adult','Choose a safe replacement'),('A child pauses by a door.','door','The child does not know the way.','Ask the familiar teacher for guidance','Stay with a trusted adult'),('A cup is pushed aside.','cup','The child does not want that drink.','Respect the choice','Ask an adult about another suitable drink'),('A puzzle is left on the table.','blocks','The child wants help with one step.','Ask which step to work on','Offer help with permission'),('A child stops running.','run','Rest is needed.','Offer a safe resting place','Ask whether water is wanted'),('A friend speaks softly.','quiet','The room is too noisy to be comfortable.','Find a quieter place if possible','Ask about lowering the noise')]
 replace('stories',6,2,[B2(p+' We do not know why.',a,[('Ask what happened',new),('Ask whether help or space is wanted',new)],[(x,'This response uses the new information while preserving choice.'),(y,'This is another possible response to the stated information.')]) for p,a,new,x,y in revision])
 # New tasks added after the initial language pass need the same localized feedback.
 for lev in D['chinese']['levels']:
  for fam in lev['families']:
   for q in fam['tasks']:
    for st in q.get('stages',[q]):
     if st.get('cue')=='Choose the answer.':st['cue']='看清提示，选择答案。'
     if st.get('mode')=='order':st['cue']='按顺序点词卡或图片。↶ 可以撤销。'
     st['retry']='再看看提示，试一试。'

 # Record generators vary the data in the browser within explicit bounds.
 for f in [1,2]:
  for q,row in zip(bank('science',3,f),measures):
   kind,a,b,c,d=row
   q['generator']={'type':'change-record','kind':kind,'delta':b-a,'question':('Which object changed?' if f==1 else 'What changed in A?')}
 for q,row in zip(bank('science',4,1),measures):
  kind,a,b,c,d=row;q['generator']={'type':'change-record','kind':kind,'delta':b-a,'question':'Which statement is supported?'}
 for q,row in zip(bank('science',5,1),measures):
  kind,a,b,c,d=row
  q['options'][0]['label']=q['options'][0]['text']='A had smaller recorded values in these trials'
  q['generator']={'type':'trial-record','kind':kind,'gap':abs(b-a)+2}
  low=2;high=low+abs(b-a)+2
  q['prompt']='Supplied '+kind+' in three trials: A '+str(low)+', '+str(low+1)+', '+str(low)+'; B '+str(high)+', '+str(high+1)+', '+str(high)+'. Which conclusion fits?'
