(function(){'use strict';
var level=1,family=0,q=null,phase=0,done=false,selected=[],order=[],question=0,history={},bags={},played={},view='levels',storyNode='start';
function el(id){return document.getElementById(id);}function clear(id){el(id).innerHTML='';}function rand(n){return Math.floor(Math.random()*n);}function shuffle(a){a=a.slice();for(var i=a.length-1;i>0;i--){var j=rand(i+1),t=a[i];a[i]=a[j];a[j]=t;}return a;}
function show(name){view=name;el('levels').hidden=name!=='levels';el('families').hidden=name!=='families';el('play').hidden=name!=='play';el('back').hidden=name==='levels';}
function text(parent,value,cls){var x=document.createElement('div');x.className=cls||'text-card';x.textContent=value;el(parent).appendChild(x);return x;}
function cardHTML(c){var h='';if(c.art&&ART[c.art]){h='<img src="'+ART[c.art]+'" alt=""'+(c.scale==='small'?' style="width:50px;height:50px;margin:25px"':'')+'>';}if(c.crop){h='<div style="height:48px;overflow:hidden">'+h+'</div>';}return h;}
function card(parent,c,fn,label){var x=document.createElement(fn?'button':'div');x.className=(fn?'':'passive ')+'card';if(fn){x.type='button';x.setAttribute('aria-label',label||c.label||'Choose picture');x.onclick=function(){el('feedback').textContent='';fn();};}else{x.setAttribute('aria-label',c.label||'Reference picture');}x.innerHTML=cardHTML(c);if(c.text||!c.art){var s=document.createElement('span');s.className='label';s.textContent=c.text||c.label;x.appendChild(s);}el(parent).appendChild(x);return x;}
function button(parent,label,fn,cls){var b=document.createElement('button');b.textContent=label;b.className=cls||'';b.onclick=function(){el('feedback').textContent='';fn();};el(parent).appendChild(b);return b;}
function loadMarks(){try{played=JSON.parse(localStorage.getItem('kll-'+CONFIG.id+'-played-v1')||'{}');if(!played||typeof played!=='object'){played={};}}catch(e){played={};}}
function levels(){show('levels');clear('levels');for(var i=0;i<6;i++){(function(l){var b=button('levels','',function(){level=l;families();},'level');var badge=document.createElement('span');badge.className='level-example';badge.textContent=String(l);b.appendChild(badge);var t=document.createElement('span');t.textContent=CONFIG.levels[l-1].name;b.appendChild(t);var s=document.createElement('small');s.textContent=CONFIG.levels[l-1].goal+' · '+CONFIG.levels[l-1].preview;b.appendChild(s);b.setAttribute('aria-label','Level '+l+': '+CONFIG.levels[l-1].name);}(i+1));}text('levels',CONFIG.intro,'guide-label');}
function families(){show('families');clear('families');text('families','Level '+level+' · '+CONFIG.levels[level-1].goal);var a=CONFIG.levels[level-1].families;for(var i=0;i<a.length;i++){(function(j){var b=button('families',a[j].name+(played[level+'-'+j]?' ✓':''),function(){family=j;question=0;next();},'family');var s=document.createElement('small');s.textContent=a[j].description;b.appendChild(s);b.setAttribute('aria-label','Activity '+(j+1)+': '+a[j].name);}(i));}}
function signature(task){return task.id;}
function next(){var key=level+'-'+family,a=CONFIG.levels[level-1].families[family].tasks,bag=bags[key]||[],recent=history[key]||[],index;if(!bag.length){bag=shuffle(a.map(function(t,i){return i;}));}index=bag.shift();if(recent.length&&a.length>1&&signature(a[index])===recent[recent.length-1]){if(bag.length){var t=index;index=bag.shift();bag.push(t);}else{index=(index+1)%a.length;}}bags[key]=bag;q=JSON.parse(JSON.stringify(a[index]));el('play').setAttribute('data-task-id',q.id);history[key]=recent.concat([signature(q)]).slice(-8);question++;phase=0;done=false;selected=[];order=[];storyNode='start';show('play');el('next').hidden=true;el('family-title').textContent=CONFIG.levels[level-1].families[family].name;el('progress').textContent='Level '+level+' · # '+question;el('guide').textContent=q.guide||CONFIG.guide;render();}
function current(){return q.stages?q.stages[phase]:q;}
function freeze(){var containers=['choices','tools'];for(var j=0;j<containers.length;j++){var a=el(containers[j]).querySelectorAll('button');for(var i=a.length-1;i>=0;i--){var x=document.createElement('div');x.className='passive '+a[i].className;x.innerHTML=a[i].innerHTML;x.setAttribute('aria-label',a[i].getAttribute('aria-label')||a[i].textContent);a[i].parentNode.replaceChild(x,a[i]);}}}
function complete(message){if(done){return;}done=true;el('feedback').textContent='✓ '+(message||current().explain||'Complete');el('cue').textContent=CONFIG.id==='chinese'?'完成了。→ 再玩同级一题，或 ← 返回。':'Complete. → Another question at this level, or ← Back.';el('next').hidden=false;freeze();clear('tools');played[level+'-'+family]=true;try{localStorage.setItem('kll-'+CONFIG.id+'-played-v1',JSON.stringify(played));}catch(e){}}
function solved(){if(q.stages&&phase<q.stages.length-1){phase++;selected=[];order=[];render();}else{complete();}}
function fail(msg){el('feedback').textContent='↺ '+(msg||current().retry||'Look at the clue and try again.');}
function validOrder(s,ids){if(s.constraints){for(var i=0;i<s.constraints.length;i++){if(ids.indexOf(s.constraints[i][0])>=ids.indexOf(s.constraints[i][1])){return false;}}return true;}var values=ids.map(function(id){return s.items[id].value||s.items[id].text||s.items[id].label;});var accepted=s.accepted||[s.items.map(function(c){return c.value||c.text||c.label;})];for(var a=0;a<accepted.length;a++){if(JSON.stringify(values)===JSON.stringify(accepted[a])){return true;}}return false;}
function renderOrder(s){clear('choices');clear('work');for(var i=0;i<order.length;i++){card('work',s.items[order[i]],null);}var remaining=[];for(i=0;i<s.items.length;i++){if(order.indexOf(i)<0){remaining.push(i);}}if(!s.displayOrder){s.displayOrder=shuffle(remaining);}for(i=0;i<s.displayOrder.length;i++){(function(id){if(order.indexOf(id)<0){card('choices',s.items[id],function(){order.push(id);renderOrder(s);if(order.length===s.items.length){if(validOrder(s,order)){solved();}else{fail(s.retry||'Try a different order. Undo the last card.');}}},'Add card '+(id+1)+': '+s.items[id].label);}}(s.displayOrder[i]));}clear('tools');if(order.length){button('tools','↶ Undo',function(){order.pop();renderOrder(s);});}hint(s);el('cue').textContent=(s.cue||'Tap cards in order.')+' ('+order.length+' / '+s.items.length+')';}
function hint(s){if(s.hint){button('tools','? Hint',function(){var old=el('tools').querySelector('.hint');if(old){old.parentNode.removeChild(old);}text('tools',s.hint,'hint');},'hint-control');}}
function render(){var s=current();clear('scene');clear('choices');clear('work');clear('tools');el('feedback').textContent='';el('cue').textContent=(q.stages?(CONFIG.id==='chinese'?'步骤 ':'Step ')+(phase+1)+' / '+q.stages.length+': ':'')+(s.cue||'Choose a picture.');if(q.stages&&phase>0){var earlier=q.stages[phase-1];if(earlier.prompt){text('scene',earlier.prompt,'text-card prior-clue');}if(earlier.scene){for(var c=0;c<earlier.scene.length;c++){card('scene',earlier.scene[c],null);}}}if(s.narration){text('scene',s.narration,'guide-label');}if(s.prompt){text('scene',s.prompt,s.promptClass||'text-card');}if(s.scene){for(var i=0;i<s.scene.length;i++){card('scene',s.scene[i],null);}}if(s.mode==='order'){renderOrder(s);return;}if(s.mode==='branch'){renderBranch();return;}if(s.mode==='predict'){renderPredict(s);return;}var indices=shuffle(s.options.map(function(c,i){return i;}));for(i=0;i<indices.length;i++){(function(id){card('choices',s.options[id],function(){if(s.mode==='multi'){if(selected.indexOf(id)>=0){selected.splice(selected.indexOf(id),1);renderSelections();return;}if(s.answers.indexOf(id)<0){fail();return;}selected.push(id);renderSelections();if(selected.length===s.answers.length){solved();}}else if(s.answers.indexOf(id)>=0){solved();}else{fail();}},'Choose option '+(id+1)+': '+s.options[id].label).setAttribute('data-option',String(id));}(indices[i]));}hint(s);}
function renderSelections(){var a=el('choices').querySelectorAll('button');for(var i=0;i<a.length;i++){var sel=selected.indexOf(Number(a[i].getAttribute('data-option')))>=0;a[i].className='card'+(sel?' selected':'');a[i].setAttribute('aria-pressed',String(sel));}el('cue').textContent=(current().cue||'Find all matching pictures.')+' ('+selected.length+' / '+current().answers.length+')';}
function renderPredict(s){s.prediction=null;var ids=shuffle(s.options.map(function(c,i){return i;}));for(var i=0;i<ids.length;i++){(function(id){card('choices',s.options[id],function(){s.prediction=id;clear('choices');text('work','Prediction: '+s.options[id].label);clear('tools');button('tools','Observe →',function(){clear('work');text('scene',s.observation);phase++;selected=[];order=[];render();},'story-choice');el('cue').textContent='Prediction saved. Choose Observe to inspect the evidence.';},'Predict option '+(id+1)+': '+s.options[id].label);}(ids[i]));}}
function renderBranch(){var node=q.nodes[storyNode];clear('scene');clear('choices');clear('tools');text('scene',node.text);if(node.art){card('scene',{art:node.art,label:node.text},null);}el('cue').textContent=node.cue||'Choose a path. More than one response may help.';if(node.end){complete(node.text);return;}for(var i=0;i<node.options.length;i++){(function(id){var opt=node.options[id];button('choices',opt.text,function(){storyNode=opt.to;renderBranch();},'story-choice').setAttribute('aria-label','Story choice '+(id+1)+': '+opt.text);}(i));}}
el('back').onclick=function(){if(view==='play'){families();}else{levels();}};el('next').onclick=function(){if(done){next();}};loadMarks();levels();
}());
